import type { Post } from "@/lib/types"

type ReadPostSeed = {
  title: string
  slug: string
  excerpt: string
  category: string
  tags: string[]
  image: string
  author: string
  avatar: string
  createdAt: string
  likes: number
  comments: number
  sections: { title: string; body: string[] }[]
}

function contentFromSections(sections: ReadPostSeed["sections"]) {
  return sections
    .flatMap((section) => [
      `## ${section.title}`,
      ...section.body,
    ])
    .join("\n\n")
}

function makePost(seed: ReadPostSeed): Post {
  return {
    id: seed.slug,
    title: seed.title,
    slug: seed.slug,
    excerpt: seed.excerpt,
    content: contentFromSections(seed.sections),
    author_name: seed.author,
    author_avatar: seed.avatar,
    category: seed.category,
    tags: seed.tags,
    image: seed.image,
    // Social proof is populated only from persisted, approved interactions.
    // Editorial seed numbers are not public evidence.
    likes: 0,
    comments: 0,
    created_at: seed.createdAt,
    product_ids: [],
  }
}

export const CATALOGUE_READ_POSTS: Post[] = [
  makePost({
    title: "Routine da dầu mụn 4 bước",
    slug: "routine-da-dau-mun-4-buoc",
    excerpt: "Một routine ngắn cho da dầu mụn: làm sạch dịu, dưỡng nhẹ, treatment có kiểm soát và chống nắng không bí.",
    category: "Skincare Routine",
    tags: ["Da dầu mụn", "Routine", "Treatment", "Chống nắng"],
    image: "/images/catalogue/skincare-foundation.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T09:00:00Z",
    likes: 428,
    comments: 39,
    sections: [
      {
        title: "Bắt đầu bằng da chịu được routine",
        body: [
          "Da dầu mụn không cần một kệ sản phẩm dài. Bốn bước đủ dùng là làm sạch dịu, dưỡng ẩm nhẹ, một treatment chính và chống nắng ban ngày. Nếu da đang đỏ rát hoặc bong, hãy bỏ treatment vài ngày và giữ hai bước phục hồi trước.",
          "- Sáng: rửa mặt nhẹ hoặc chỉ rửa nước nếu da không quá dầu, dưỡng mỏng, chống nắng ráo.\n- Tối: làm sạch kỹ kem chống nắng, dưỡng nhẹ, treatment theo lịch.",
        ],
      },
      {
        title: "Treatment chỉ nên có một vai chính",
        body: [
          "Nếu vấn đề chính là mụn ẩn và đầu đen, BHA hoặc retinoid tần suất thấp thường hợp logic hơn việc scrub mạnh. Nếu có mụn viêm nhẹ, benzoyl peroxide hoặc azelaic acid có thể là lựa chọn đáng đọc kỹ. Không nên bắt đầu BHA, retinoid và benzoyl peroxide cùng một tuần nếu da chưa quen.",
          "Một lịch dễ sống: treatment 2-3 tối/tuần, các tối còn lại dưỡng phục hồi. Sau 2 tuần nếu da ổn, tăng tần suất chậm. Khi da châm chích kéo dài, đỏ hoặc bong rõ, giảm tần suất thay vì đổi sang hoạt chất mạnh hơn.",
        ],
      },
      {
        title: "Dấu hiệu routine đang đi đúng hướng",
        body: [
          "Da ít căng sau rửa, ít đỏ sau treatment, mụn mới giảm dần và thâm không đậm thêm là tín hiệu tốt. Kết quả trị mụn thường cần vài tuần; đổi routine mỗi vài ngày sẽ làm bạn mất dữ liệu.",
          "Nếu mụn đau sâu, để sẹo, lan nhanh hoặc không cải thiện sau nhiều tuần chăm đúng, đừng tiếp tục mua thêm serum. Lúc đó nên xem mụn như vấn đề da liễu cần bác sĩ.",
        ],
      },
    ],
  }),
  makePost({
    title: "Da treatment bị yếu nên phục hồi ra sao",
    slug: "da-treatment-bi-yeu-nen-phuc-hoi-ra-sao",
    excerpt: "Cách nhận biết da quá tải treatment và protocol phục hồi hàng rào bảo vệ da trước khi quay lại hoạt chất.",
    category: "Chăm Sóc Da",
    tags: ["Phục hồi da", "Barrier", "Treatment", "Da nhạy cảm"],
    image: "/images/catalogue/skincare-foundation.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T09:10:00Z",
    likes: 392,
    comments: 31,
    sections: [
      {
        title: "Da yếu không phải lúc nào cũng là dị ứng",
        body: [
          "Da treatment bị yếu thường có các dấu hiệu: rát khi bôi sản phẩm từng dùng ổn, bong quanh miệng/mũi, đỏ dai dẳng, châm chích kéo dài, nổi mụn li ti hoặc da bóng căng bất thường. Nguyên nhân hay gặp là dùng quá nhiều acid, retinoid, peel tại nhà hoặc làm sạch quá gắt.",
          "Việc cần làm đầu tiên là giảm tải. Dừng sản phẩm mạnh trong vài ngày đến vài tuần tùy mức độ, giữ routine càng đơn giản càng tốt: làm sạch dịu, dưỡng phục hồi, chống nắng.",
        ],
      },
      {
        title: "Routine phục hồi tối giản",
        body: [
          "- Cleanser dịu, không làm da căng rít.\n- Kem dưỡng có humectant và lipid hỗ trợ barrier như glycerin, panthenol, ceramide, squalane hoặc centella nếu da hợp.\n- Chống nắng dễ chịu, không cay mắt, không quá bí.",
          "Đừng cố thêm nhiều serum phục hồi cùng lúc. Da yếu cần ít biến số để hồi lại, không cần thêm một routine 10 bước. Nếu dưỡng nào cũng xót, ưu tiên công thức cơ bản và thử trên vùng nhỏ.",
        ],
      },
      {
        title: "Khi nào quay lại treatment",
        body: [
          "Chỉ quay lại khi da hết rát, ít đỏ, không còn bong rõ và dưỡng/chống nắng không làm châm chích. Bắt đầu bằng tần suất thấp hơn trước: một đến hai tối mỗi tuần, lượng nhỏ, không phối thêm acid hoặc retinoid khác cùng tối.",
          "Nếu da sưng, nóng, chảy dịch, nổi mẩn lan rộng hoặc đau nhiều, nên dừng tự xử lý và gặp bác sĩ da liễu.",
        ],
      },
    ],
  }),
  makePost({
    title: "Kem chống nắng không bí cho khí hậu nóng ẩm",
    slug: "kem-chong-nang-khong-bi-cho-khi-hau-nong-am",
    excerpt: "Cách chọn sunscreen đủ bảo vệ nhưng vẫn dễ dùng mỗi ngày trong thời tiết nóng ẩm.",
    category: "Chống Nắng",
    tags: ["SPF", "Da dầu", "Nóng ẩm", "Sunscreen"],
    image: "/images/catalogue/acne-sun-education.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T09:20:00Z",
    likes: 501,
    comments: 44,
    sections: [
      {
        title: "Không bí bắt đầu từ texture",
        body: [
          "Ở khí hậu nóng ẩm, sunscreen tốt không chỉ là SPF cao. Nó phải đủ dễ chịu để bạn dùng đủ lượng: không quá dính, không cay mắt, không vón khi thoa lại và không làm da bí sau vài giờ.",
          "Da dầu thường hợp gel, fluid, milk mỏng hoặc finish semi-matte. Da khô có thể cần lotion/cream nhẹ hơn là finish quá khô. Nếu đang treatment, hãy ưu tiên sản phẩm ít gây châm chích hơn là chỉ chọn theo quảng cáo kiềm dầu.",
        ],
      },
      {
        title: "Cách test trước khi mua fullsize",
        body: [
          "- Test quanh mắt để xem cay không.\n- Thoa đủ lượng trên nửa mặt để xem bóng, bí, vón sau 3-4 giờ.\n- Thử dưới khẩu trang hoặc khi ra mồ hôi nếu đó là bối cảnh dùng thật.",
          "Nếu một sản phẩm rất đẹp lúc mới thoa nhưng khiến bạn không muốn bôi lại, nó không phải sunscreen tốt cho routine của bạn.",
        ],
      },
      {
        title: "Đừng quên chống nắng vật lý",
        body: [
          "Mũ, kính, áo chống nắng và tránh nắng gắt vẫn quan trọng. Khi mồ hôi nhiều, đi biển hoặc vận động ngoài trời, hãy chọn sản phẩm có kháng nước và thoa lại theo hướng dẫn.",
          "Với thâm mụn hoặc nám, chống nắng đều quan trọng hơn việc đổi serum làm sáng liên tục.",
        ],
      },
    ],
  }),
  makePost({
    title: "Mụn ẩn khác gì purging",
    slug: "mun-an-khac-gi-purging",
    excerpt: "Phân biệt mụn ẩn, purging và kích ứng để không dùng sai treatment.",
    category: "Trị Mụn",
    tags: ["Mụn ẩn", "Purging", "BHA", "Retinoid"],
    image: "/images/catalogue/acne-sun-education.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T09:30:00Z",
    likes: 366,
    comments: 28,
    sections: [
      { title: "Mụn ẩn là bít tắc chưa viêm rõ", body: ["Mụn ẩn thường là nốt gồ nhỏ dưới da, ít đau, hay gặp ở vùng trán, cằm, má hoặc nơi dễ bí. Nó liên quan dầu, tế bào chết, mỹ phẩm bí, ma sát hoặc làm sạch chưa phù hợp.", "Purging lại là hiện tượng một số hoạt chất thúc đẩy turnover làm nhân mụn có sẵn trồi lên nhanh hơn. Nó thường xảy ra ở vùng vốn hay có mụn, không phải bất kỳ chỗ nào trên mặt."] },
      { title: "Kích ứng không phải purging", body: ["Nếu mụn li ti lan ra vùng lạ, kèm rát, ngứa, đỏ hoặc bong mạnh, hãy nghĩ đến kích ứng. Lúc này tăng treatment thường làm da tệ hơn.", "- Purging: vùng quen nổi mụn, có hoạt chất turnover, giảm dần theo thời gian.\n- Kích ứng: rát/ngứa/đỏ rõ, lan vùng lạ, da yếu đi.\n- Mụn ẩn dai dẳng: cần xem lại bí tắc, makeup, tóc, khẩu trang, cleanser và dưỡng."] },
      { title: "Cách xử lý thực tế", body: ["Với mụn ẩn, chọn một hướng chính như BHA hoặc retinoid tần suất thấp. Giữ dưỡng phục hồi và chống nắng. Đừng scrub hoặc nặn hàng loạt.", "Nếu sau 6-8 tuần không cải thiện, mụn viêm nhiều hơn hoặc để sẹo, nên gặp bác sĩ da liễu để tránh vòng lặp mua treatment không kiểm soát."] },
    ],
  }),
  makePost({
    title: "BHA, benzoyl peroxide, azelaic acid chọn thế nào",
    slug: "bha-benzoyl-peroxide-azelaic-acid-chon-the-nao",
    excerpt: "Ba hoạt chất trị mụn phổ biến có vai trò khác nhau; chọn sai hoặc phối quá nhanh dễ làm da yếu.",
    category: "Ingredient Radar",
    tags: ["BHA", "Benzoyl peroxide", "Azelaic acid", "Trị mụn"],
    image: "/images/catalogue/acne-sun-education.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T09:40:00Z",
    likes: 441,
    comments: 36,
    sections: [
      { title: "BHA hợp logic bít tắc", body: ["BHA thường được chọn khi vấn đề chính là dầu, đầu đen, mụn ẩn hoặc bề mặt da dễ bí. Người mới nên dùng chậm, tránh phối ngay với retinoid hoặc peel mạnh.", "Nếu da khô căng sau BHA, vấn đề không phải cứ tăng nồng độ. Hãy giảm tần suất và xem lại dưỡng phục hồi."] },
      { title: "Benzoyl peroxide hợp mụn viêm nhẹ", body: ["Benzoyl peroxide thường được dùng cho mụn viêm vì có cơ chế hỗ trợ giảm vi khuẩn liên quan mụn. Nó có thể làm khô, châm chích và bạc màu vải, nên cần dùng đúng vùng và theo dõi phản ứng.", "Không cần bôi toàn mặt nếu chỉ có vài nốt viêm. Với da nhạy cảm, dạng wash-off hoặc nồng độ thấp có thể dễ vào hơn."] },
      { title: "Azelaic acid là lựa chọn cân bằng", body: ["Azelaic acid thường được đọc trong bối cảnh mụn, đỏ và thâm sau mụn. Nó không phải hoạt chất 'nhẹ tuyệt đối', nhưng nhiều người dung nạp tốt hơn các treatment quá gắt.", "Dù chọn hoạt chất nào, nguyên tắc vẫn là một vai chính, tần suất thấp, chống nắng và phục hồi. Mụn nang hoặc sẹo không nên chỉ tự xử lý bằng mỹ phẩm."] },
    ],
  }),
  makePost({
    title: "Mụn lưng và thói quen tóc/bodycare",
    slug: "mun-lung-va-thoi-quen-toc-bodycare",
    excerpt: "Mụn lưng thường liên quan mồ hôi, dầu xả, quần áo bó và bodycare nhiều hơn bạn nghĩ.",
    category: "Bodycare",
    tags: ["Mụn lưng", "Bodycare", "Haircare"],
    image: "/images/catalogue/hair-body-grooming.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T09:50:00Z",
    likes: 289,
    comments: 22,
    sections: [
      { title: "Đừng chỉ đổi sữa tắm", body: ["Mụn lưng có thể đến từ mồ hôi sau tập, áo bó, balo ma sát, dầu xả chảy xuống lưng hoặc sản phẩm tạo kiểu tóc. Nếu chỉ mua body wash trị mụn mà không sửa trigger, mụn dễ quay lại.", "Hãy tắm body sau khi xả tóc, thay áo sau vận động và tránh để dầu dưỡng tóc dính vào lưng."] },
      { title: "Treatment body nên vào chậm", body: ["Body wash có BHA hoặc benzoyl peroxide có thể hữu ích, nhưng vẫn có thể làm khô hoặc kích ứng. Không dùng acid mạnh ngay sau wax/cạo hoặc khi da đang trầy xước.", "- Tắm sau vận động.\n- Xả sạch dầu xả.\n- Chọn áo thoáng.\n- Dùng treatment body vài lần/tuần rồi tăng nếu da ổn."] },
      { title: "Khi nào nên đi khám", body: ["Nếu mụn lưng đau, có mủ, lan rộng, để sẹo hoặc giống viêm nang lông nặng, nên gặp bác sĩ. Bodycare tại nhà có giới hạn khi viêm đã mạnh."] },
    ],
  }),
  makePost({
    title: "Kem chống nắng da dầu không bí",
    slug: "kem-chong-nang-da-dau-khong-bi",
    excerpt: "Checklist chọn chống nắng cho da dầu: finish, màng lọc, thoa lại và cách test bí da.",
    category: "Chống Nắng",
    tags: ["Da dầu", "Chống nắng", "SPF"],
    image: "/images/catalogue/acne-sun-education.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T10:00:00Z",
    likes: 377,
    comments: 33,
    sections: [
      { title: "Da dầu cần finish dùng được đủ lượng", body: ["Finish ráo không có nghĩa là làm da khô căng. Kem chống nắng cho da dầu nên mỏng, ít trượt, ít cay mắt, không vón khi layer với dưỡng hoặc makeup.", "Nếu sản phẩm quá khô, da có thể bong quanh mũi/miệng khi dùng treatment. Nếu quá ẩm, bạn sẽ ngại thoa đủ lượng."] },
      { title: "Test trong bối cảnh thật", body: ["Hãy test khi đeo khẩu trang, đi nắng, ngồi văn phòng và thoa lại. Một sunscreen đẹp lúc mới bôi nhưng bóng dầu sau 2 giờ có thể không hợp lịch sống của bạn.", "- Không cay mắt.\n- Không bí khi dùng đủ lượng.\n- Không vón với dưỡng.\n- Có thể thoa lại mà không bẩn mặt."] },
      { title: "Dùng thêm che chắn", body: ["Da dầu mụn rất dễ thâm sau viêm nếu chống nắng kém. Mũ, kính, khẩu trang chống nắng và tránh nắng gắt giúp giảm áp lực cho sunscreen, nhất là khi treatment."] },
    ],
  }),
  makePost({
    title: "Thâm mụn bao lâu mờ",
    slug: "tham-mun-bao-lau-mo",
    excerpt: "Thâm mụn cần thời gian, chống nắng và kiểm soát mụn mới; không nên kỳ vọng trắng nhanh.",
    category: "Chăm Sóc Da",
    tags: ["Thâm mụn", "PIH", "Sáng da"],
    image: "/images/catalogue/acne-sun-education.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T10:10:00Z",
    likes: 422,
    comments: 41,
    sections: [
      { title: "Thâm mụn là dấu vết sau viêm", body: ["Thâm mụn thường đậm hơn khi mụn bị nặn, viêm lâu hoặc chống nắng kém. Vết thâm nông có thể cải thiện theo tuần, nhưng nhiều trường hợp cần vài tháng.", "Điều quan trọng nhất là không tạo thêm mụn viêm mới. Nếu mụn vẫn bùng liên tục, serum sáng da chỉ đang xử lý phần ngọn."] },
      { title: "Routine nên ưu tiên gì", body: ["Chống nắng đều, dưỡng phục hồi và một hoạt chất làm sáng vừa sức là nền. Vitamin C, niacinamide, azelaic acid hoặc tranexamic acid có thể được cân nhắc tùy da, nhưng không nên thêm tất cả cùng lúc.", "Da đang rát hoặc bong không nên bị ép dùng acid làm sáng mạnh. Kích ứng có thể làm sắc tố dai hơn."] },
      { title: "Khi thâm không chỉ là thâm", body: ["Nếu sau mụn có lõm, đỏ dai dẳng, mảng sắc tố lan rộng hoặc nghi nám, hãy đọc lại vấn đề. Sẹo và nám cần chiến lược khác thâm mụn thông thường."] },
    ],
  }),
  makePost({
    title: "Nám sau sinh nên chăm tại nhà hay đi clinic",
    slug: "nam-sau-sinh-cham-tai-nha-hay-di-clinic",
    excerpt: "Nám sau sinh cần chống nắng, phục hồi và thận trọng với treatment; clinic không nên là bước đầu vội vàng.",
    category: "Clinic / Treatment",
    tags: ["Nám", "Sau sinh", "Clinic", "Chống nắng"],
    image: "/images/catalogue/acne-sun-education.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T10:20:00Z",
    likes: 318,
    comments: 27,
    sections: [
      { title: "Đầu tiên là chống nắng nghiêm túc", body: ["Nám sau sinh thường liên quan hormone, nắng và cơ địa. Chăm tại nhà nên bắt đầu từ chống nắng rộng phổ, che chắn vật lý, dưỡng phục hồi và routine ít kích ứng.", "Nếu đang cho con bú hoặc còn trong giai đoạn sau sinh, đừng tự dùng hoạt chất mạnh khi chưa kiểm tra độ an toàn."] },
      { title: "Clinic có vai trò nhưng phải đúng thời điểm", body: ["Peel, laser hoặc thuốc bôi mạnh cần đánh giá trực tiếp, vì da dễ tăng sắc tố sau viêm có thể đậm hơn nếu làm sai chỉ định. Clinic đáng tin phải hỏi tiền sử, routine, thai kỳ/sau sinh, thuốc đang dùng và giải thích downtime.", "Nếu tư vấn chỉ nói gói liệu trình mà không nói rủi ro, nên chậm lại."] },
      { title: "Khi nào nên đi khám", body: ["Nám lan nhanh, đậm lên rõ, không cải thiện dù chống nắng tốt hoặc ảnh hưởng nhiều đến tâm lý là lúc nên gặp bác sĩ da liễu. Mục tiêu là kiểm soát bền, không phải lột trắng nhanh."] },
    ],
  }),
  makePost({
    title: "Niacinamide có cần nồng độ cao không",
    slug: "niacinamide-co-can-nong-do-cao-khong",
    excerpt: "Niacinamide không phải cứ cao là tốt; nền da, công thức và tần suất quan trọng hơn con số trên nhãn.",
    category: "Ingredient Radar",
    tags: ["Niacinamide", "Hoạt chất", "Da dầu", "Phục hồi"],
    image: "/images/catalogue/skincare-foundation.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T10:30:00Z",
    likes: 336,
    comments: 25,
    sections: [
      { title: "Nồng độ cao không tự động tốt hơn", body: ["Niacinamide được nhắc đến trong nhiều mục tiêu như hỗ trợ barrier, dầu, thâm và đều màu. Nhưng trải nghiệm phụ thuộc công thức, nền da và sản phẩm đi kèm, không chỉ phần trăm.", "Một số da dễ đỏ hoặc châm chích với nồng độ cao. Nếu da đang treatment, chọn nồng độ vừa phải và công thức dịu có thể bền hơn."] },
      { title: "Đọc sản phẩm theo routine", body: ["Nếu toner, serum và kem dưỡng đều có niacinamide, tổng tải có thể nhiều hơn bạn nghĩ. Không nhất thiết phải mua thêm serum 10-20% chỉ vì hoạt chất này đang nổi.", "Hãy hỏi: vấn đề chính là gì, da đang khỏe không, routine đã có những active nào?"] },
      { title: "Cách thử an toàn", body: ["Thử trên vùng nhỏ, dùng cách ngày trong tuần đầu và không đổi nhiều sản phẩm cùng lúc. Nếu có đỏ rát kéo dài, giảm tần suất hoặc đổi sang công thức đơn giản hơn."] },
    ],
  }),
  makePost({
    title: "Retinol cho người mới",
    slug: "retinol-cho-nguoi-moi",
    excerpt: "Retinol cần lịch vào chậm, phục hồi và chống nắng; người mới không nên bắt đầu bằng nồng độ mạnh.",
    category: "Ingredient Radar",
    tags: ["Retinol", "Retinoid", "Anti-aging", "Treatment"],
    image: "/images/catalogue/skincare-foundation.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T10:40:00Z",
    likes: 468,
    comments: 47,
    sections: [
      { title: "Retinol không phải bước bắt buộc cho mọi người", body: ["Retinol/retinoid có thể hỗ trợ mụn, texture và lão hóa, nhưng không phải ai cũng cần dùng ngay. Người mới nên bắt đầu khi routine nền đã ổn và da chịu được dưỡng/chống nắng hằng ngày.", "Đang mang thai/sau sinh hoặc có bệnh da đang điều trị cần hỏi bác sĩ trước khi dùng nhóm retinoid."] },
      { title: "Lịch vào chậm", body: ["Bắt đầu 1-2 tối/tuần, lượng nhỏ, tránh bôi sát khóe mũi/mắt/miệng nếu dễ rát. Các tối còn lại dưỡng phục hồi. Không phối acid mạnh ngay từ đầu.", "- Tuần 1-2: 1-2 lần/tuần.\n- Tuần 3-4: tăng nếu da không rát/bong nhiều.\n- Luôn chống nắng ban ngày."] },
      { title: "Dấu hiệu cần giảm", body: ["Bong nhẹ có thể xảy ra, nhưng rát kéo dài, đỏ mạnh, ngứa hoặc mụn viêm lan rộng là dấu hiệu quá tải. Giảm tần suất và phục hồi trước khi nghĩ đến tăng nồng độ."] },
    ],
  }),
  makePost({
    title: "Ceramide và B5 phục hồi khác gì nhau",
    slug: "ceramide-va-b5-phuc-hoi-khac-gi-nhau",
    excerpt: "Ceramide và B5 đều nằm trong nhóm phục hồi nhưng vai trò và cảm giác dùng không giống nhau.",
    category: "Ingredient Radar",
    tags: ["Ceramide", "B5", "Panthenol", "Phục hồi"],
    image: "/images/catalogue/skincare-foundation.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T10:50:00Z",
    likes: 351,
    comments: 26,
    sections: [
      { title: "Ceramide thiên về lipid hàng rào da", body: ["Ceramide là nhóm lipid tự nhiên trong hàng rào bảo vệ da. Sản phẩm có ceramide thường hợp khi da khô, yếu barrier, dễ mất nước hoặc dùng treatment.", "Cảm giác có thể từ lotion nhẹ đến cream dày tùy công thức. Da dầu vẫn có thể dùng ceramide nếu texture không quá bí."] },
      { title: "B5/panthenol thiên về làm dịu và hỗ trợ phục hồi", body: ["Panthenol thường được dùng trong sản phẩm làm dịu, cấp ẩm và hỗ trợ cảm giác da dễ chịu hơn. Nó không thay thế toàn bộ lipid barrier nhưng rất hữu ích khi da rát nhẹ hoặc căng.", "Nhiều routine phục hồi tốt phối cả humectant, panthenol, ceramide và chất khóa ẩm vừa đủ."] },
      { title: "Chọn theo cảm giác da", body: ["Da khô bong có thể cần cream lipid hơn; da dầu treatment có thể thích serum B5 hoặc gel cream nhẹ; da rát nhiều nên tối giản và tránh hương liệu mạnh."] },
    ],
  }),
  makePost({
    title: "Serum phục hồi đáng mua",
    slug: "serum-phuc-hoi-dang-mua",
    excerpt: "Tiêu chí đọc serum phục hồi: thành phần làm dịu, texture, khả năng layer và mức cần thiết trong routine.",
    category: "Review Sản Phẩm",
    tags: ["Serum phục hồi", "B5", "Ceramide"],
    image: "/images/products/the-ordinary-hyaluronic-acid-2-b5.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T11:00:00Z",
    likes: 294,
    comments: 19,
    sections: [
      { title: "Đáng mua khi nó giải quyết đúng vấn đề", body: ["Serum phục hồi đáng mua khi da đang treatment, căng rát nhẹ, thiếu nước hoặc cần layer trước kem dưỡng. Nếu da đã ổn với kem dưỡng, serum phục hồi không phải lúc nào cũng cần.", "Đừng mua chỉ vì chữ phục hồi. Hãy xem thành phần, texture và cách nó nằm trong routine."] },
      { title: "Tiêu chí chọn", body: ["Ưu tiên công thức dễ layer, ít gây bí, có humectant/làm dịu như glycerin, panthenol, centella, HA hoặc hỗ trợ barrier như ceramide tùy nhu cầu.", "- Da dầu: serum mỏng, không dính.\n- Da khô: serum + cream khóa ẩm.\n- Da nhạy cảm: ít hương liệu, patch test."] },
      { title: "Khi serum không đủ", body: ["Nếu da đang viêm nặng, bong đau hoặc nghi dị ứng, serum phục hồi không thay thế đánh giá y khoa. Nó là sản phẩm hỗ trợ, không phải thuốc chữa mọi kích ứng."] },
    ],
  }),
  makePost({
    title: "Retinol drugstore vs luxury",
    slug: "retinol-drugstore-vs-luxury",
    excerpt: "Retinol đắt hơn không mặc định hiệu quả hơn; điểm khác thường nằm ở công thức, bao bì và trải nghiệm.",
    category: "Review Sản Phẩm",
    tags: ["Retinol", "Drugstore", "Luxury"],
    image: "/images/catalogue/skincare-foundation.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T11:10:00Z",
    likes: 306,
    comments: 24,
    sections: [
      { title: "So bằng công thức, không chỉ giá", body: ["Retinol drugstore có thể đủ tốt nếu nồng độ hợp, bao bì ổn và công thức dễ dùng. Luxury có thể hơn ở texture, cảm giác, hệ dẫn hoặc thành phần hỗ trợ, nhưng không đảm bảo hợp da hơn.", "Người mới nên ưu tiên dễ dung nạp hơn là mạnh nhất."] },
      { title: "Bao bì và độ ổn định", body: ["Retinoid nhạy với ánh sáng/không khí ở mức khác nhau. Bao bì kín, hướng dẫn dùng rõ và hạn dùng hợp lý quan trọng hơn thiết kế đẹp.", "Nếu sản phẩm không nói rõ cách dùng, tần suất hoặc cảnh báo, hãy thận trọng dù giá nào."] },
      { title: "Khi nào nên nâng cấp", body: ["Nâng cấp khi bạn đã dùng đều, biết da chịu được retinoid và muốn texture/experience tốt hơn. Nếu da đang rát, luxury cũng không cứu được cách dùng sai."] },
    ],
  }),
  makePost({
    title: "Kem chống nắng dưới 300k cho da dầu",
    slug: "kem-chong-nang-duoi-300k-cho-da-dau",
    excerpt: "Khung chọn sunscreen bình dân cho da dầu: không cay mắt, không bí, dễ thoa lại và hợp khí hậu nóng ẩm.",
    category: "Review Sản Phẩm",
    tags: ["Chống nắng", "Da dầu", "Drugstore"],
    image: "/images/hero-sunscreen.png",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T11:20:00Z",
    likes: 512,
    comments: 58,
    sections: [
      { title: "Dưới 300k vẫn phải đủ tiêu chí", body: ["Giá dễ chịu không có nghĩa chấp nhận bí, cay mắt hoặc vón. Với da dầu, hãy ưu tiên texture mỏng, finish ráo vừa, không quá trắng và có thể thoa lại trong ngày.", "Đọc review từ người có da dầu trong khí hậu nóng ẩm sẽ hữu ích hơn điểm số chung."] },
      { title: "Checklist thử sản phẩm", body: ["- Có bị cay mắt khi ra mồ hôi không?\n- Có bóng dầu sau 2-3 giờ không?\n- Có vón với dưỡng ẩm không?\n- Có thoa lại được mà không bẩn mặt không?", "Nếu một sản phẩm rẻ nhưng bạn không dùng đủ lượng, chi phí thật vẫn là lãng phí."] },
      { title: "Không chỉ dựa vào sunscreen", body: ["Mũ, kính, khẩu trang chống nắng và tránh nắng gắt giúp giảm áp lực cho da dầu. Đặc biệt nếu đang trị mụn/thâm, che chắn vật lý rất đáng làm."] },
    ],
  }),
  makePost({
    title: "Mụn lưng có liên quan dầu xả không",
    slug: "mun-lung-co-lien-quan-dau-xa-khong",
    excerpt: "Dầu xả và sản phẩm tóc có thể góp phần gây bí lưng nếu không xả sạch hoặc dính vào da sau tắm.",
    category: "Bodycare",
    tags: ["Mụn lưng", "Dầu xả", "Haircare"],
    image: "/images/catalogue/hair-body-grooming.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T11:30:00Z",
    likes: 281,
    comments: 21,
    sections: [
      { title: "Có thể có, nhưng không phải mọi trường hợp", body: ["Dầu xả, mask tóc, leave-in hoặc dầu dưỡng có thể chảy xuống lưng và để lại residue. Với người dễ bí, điều này có thể góp phần làm mụn lưng dai dẳng.", "Tuy vậy mụn lưng còn liên quan mồ hôi, quần áo, hormone, viêm nang lông và vệ sinh sau vận động."] },
      { title: "Cách kiểm tra đơn giản", body: ["Gội/xả tóc trước, kẹp tóc lên, sau đó tắm body sau cùng. Đổi áo sau tập, giặt khăn/ga thường xuyên và tránh để tóc ướt dính lưng.", "Theo dõi 2-4 tuần. Nếu mụn giảm, bạn đã tìm được một trigger quan trọng."] },
      { title: "Khi cần treatment", body: ["Nếu vẫn còn mụn, có thể cân nhắc body wash có BHA hoặc benzoyl peroxide. Mụn đau, mủ, lan rộng hoặc để sẹo nên đi khám."] },
    ],
  }),
  makePost({
    title: "Routine body sáng da an toàn",
    slug: "routine-body-sang-da-an-toan",
    excerpt: "Body sáng da nên đi từ chống nắng vùng hở, dưỡng ẩm, acid nhẹ và giảm ma sát.",
    category: "Bodycare",
    tags: ["Bodycare", "Sáng da", "AHA", "Chống nắng"],
    image: "/images/catalogue/hair-body-grooming.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T11:40:00Z",
    likes: 339,
    comments: 32,
    sections: [
      { title: "Sáng da body không phải lột trắng", body: ["Mục tiêu an toàn là đều màu hơn, da mịn hơn và giảm thâm do ma sát/nắng. Những sản phẩm bong lột nhanh hoặc claim trắng cấp tốc cần được đọc rất thận trọng.", "Vùng tay, cổ, chân tiếp xúc nắng sẽ khó đều màu nếu không chống nắng."] },
      { title: "Routine dễ duy trì", body: ["- Tắm sạch nhưng không chà mạnh.\n- Dưỡng body hằng ngày bằng lotion dễ thấm.\n- Thêm AHA/urea vài lần mỗi tuần nếu da sần hoặc xỉn.\n- Chống nắng vùng hở khi ra ngoài.", "Vùng nách/bikini vừa cạo/wax không nên dùng acid mạnh ngay."] },
      { title: "Đọc nguyên nhân thâm", body: ["Thâm body có thể do nắng, ma sát, viêm nang lông, cạo/wax hoặc kích ứng deodorant. Nếu không sửa nguyên nhân, lotion sáng da chỉ cải thiện một phần."] },
    ],
  }),
  makePost({
    title: "Viêm nang lông nên dùng AHA, BHA hay urea",
    slug: "viem-nang-long-nen-dung-aha-bha-hay-urea",
    excerpt: "AHA, BHA và urea có vai trò khác nhau trong da sần, lông mọc ngược và viêm nang lông nhẹ.",
    category: "Bodycare",
    tags: ["Viêm nang lông", "AHA", "BHA", "Urea"],
    image: "/images/catalogue/hair-body-grooming.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T11:50:00Z",
    likes: 297,
    comments: 23,
    sections: [
      { title: "Gọi đúng vấn đề trước", body: ["Da sần KP, lông mọc ngược và viêm nang lông không hoàn toàn giống nhau. KP thường là sần nhỏ đều ở tay/đùi; lông mọc ngược liên quan cạo/wax; viêm nang lông có thể đỏ, đau, mủ.", "Nếu có mủ đau lan rộng, đừng tự xem là da sần thông thường."] },
      { title: "Chọn hoạt chất theo mục tiêu", body: ["AHA hỗ trợ bề mặt sần/xỉn; BHA hợp logic dầu/bít tắc hơn; urea giúp làm mềm lớp sừng và cấp ẩm. Nhiều người body sần hợp urea hoặc AHA nhẹ hơn là scrub mạnh.", "Bắt đầu 2-3 lần/tuần, tăng chậm, dưỡng ẩm đều."] },
      { title: "Giảm trigger cơ học", body: ["Dao cạo cùn, quần áo bó, ma sát và wax/cạo quá sát có thể làm vấn đề kéo dài. Treatment sẽ hiệu quả hơn nếu sửa trigger."] },
    ],
  }),
  makePost({
    title: "Gàu dầu hay da đầu khô",
    slug: "gau-dau-hay-da-dau-kho",
    excerpt: "Gàu dầu, da đầu khô và viêm da đầu cần cách đọc khác nhau trước khi đổi dầu gội.",
    category: "Chăm Sóc Tóc",
    tags: ["Gàu", "Da đầu", "Haircare"],
    image: "/images/catalogue/hair-body-grooming.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T12:00:00Z",
    likes: 266,
    comments: 18,
    sections: [
      { title: "Không phải vảy nào cũng giống nhau", body: ["Da đầu khô thường có vảy nhỏ, cảm giác căng, dễ xuất hiện khi gội quá mạnh hoặc thời tiết khô. Gàu dầu thường có vảy dính hơn, da đầu nhanh bết, có thể ngứa.", "Đỏ rát, đau, chảy dịch hoặc vảy dày dai dẳng cần được đánh giá kỹ hơn."] },
      { title: "Dầu gội treatment cần lịch dùng", body: ["Dầu gội trị gàu không phải lúc nào cũng dùng hằng ngày. Hãy đọc hướng dẫn, để sản phẩm tiếp xúc đủ thời gian nếu cần, và dùng dầu xả ở thân/ngọn tóc để tránh khô.", "Nếu chỉ gội thật mạnh, da đầu có thể kích ứng mà vẫn bết lại."] },
      { title: "Khi nên đi khám", body: ["Gàu kèm đỏ đau, rụng tóc nhiều, đóng mảng, chảy dịch hoặc không cải thiện sau vài tuần chăm đúng là lúc nên gặp bác sĩ da liễu."] },
    ],
  }),
  makePost({
    title: "Rụng tóc nam khi nào nên đi khám",
    slug: "rung-toc-nam-khi-nao-nen-di-kham",
    excerpt: "Rụng tóc nam cần đọc mẫu rụng, tốc độ và triệu chứng da đầu trước khi mua serum mọc tóc.",
    category: "Chăm Sóc Tóc",
    tags: ["Rụng tóc", "Nam giới", "Da đầu"],
    image: "/images/catalogue/hair-body-grooming.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T12:10:00Z",
    likes: 312,
    comments: 29,
    sections: [
      { title: "Nhìn mẫu rụng", body: ["Rụng vùng thái dương, đỉnh đầu hoặc đường ngôi rộng dần có thể khác rụng lan tỏa sau stress. Rụng từng mảng tròn lại là dấu hiệu nên khám sớm.", "Serum mọc tóc viral không thay thế chẩn đoán nguyên nhân."] },
      { title: "Dữ liệu cần ghi lại", body: ["Chụp ảnh đường chân tóc, đỉnh đầu và vùng rụng trong cùng ánh sáng mỗi tháng. Ghi lại stress, thuốc mới, bệnh gần đây, gàu/ngứa/đau da đầu.", "Thông tin này giúp bác sĩ đánh giá tốt hơn nếu cần đi khám."] },
      { title: "Dấu hiệu nên đi khám", body: ["Rụng nhanh, rụng từng mảng, da đầu đau/ngứa/vảy, rụng kèm mệt mỏi hoặc thay đổi sức khỏe toàn thân. Đi sớm giúp giữ nhiều lựa chọn hơn."] },
    ],
  }),
  makePost({
    title: "Bond repair có đáng tiền cho tóc tẩy nhuộm",
    slug: "bond-repair-co-dang-tien-cho-toc-tay-nhuom",
    excerpt: "Bond repair có thể hỗ trợ tóc tẩy nhuộm, nhưng không thay thế giảm nhiệt, dưỡng và cắt bỏ phần hư tổn nặng.",
    category: "Chăm Sóc Tóc",
    tags: ["Bond repair", "Tóc tẩy", "Haircare"],
    image: "/images/catalogue/hair-body-grooming.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T12:20:00Z",
    likes: 247,
    comments: 17,
    sections: [
      { title: "Tóc hư tổn không tự lành như da", body: ["Tẩy nhuộm, nhiệt và kéo căng làm sợi tóc yếu, khô, xơ và dễ gãy. Bond repair có thể cải thiện cảm giác và hỗ trợ một số liên kết, nhưng không biến tóc hư nặng thành tóc nguyên bản.", "Giảm nguồn hư tổn vẫn là nền: ít nhiệt hơn, bảo vệ nhiệt, chải nhẹ và cắt phần chẻ nặng."] },
      { title: "Khi bond repair đáng mua", body: ["Đáng cân nhắc nếu tóc tẩy nhuộm, dễ đứt, xơ rối và bạn đã có dầu gội/xả cơ bản ổn. Không đáng nếu bạn vẫn dùng nhiệt cao hằng ngày mà không bảo vệ.", "Dùng theo hướng dẫn; nhiều hơn không luôn tốt hơn."] },
      { title: "Phối với routine tóc", body: ["Bond repair nên đi cùng mask/conditioner, leave-in và heat protectant. Với da đầu dầu, chỉ dùng sản phẩm dưỡng ở thân/ngọn để tránh bết."] },
    ],
  }),
  makePost({
    title: "Base makeup cho da dầu nóng ẩm",
    slug: "base-makeup-cho-da-dau-nong-am",
    excerpt: "Layer nền cho da dầu trong khí hậu nóng ẩm: prep mỏng, nền vừa đủ, set có chọn lọc.",
    category: "Trang Điểm",
    tags: ["Base makeup", "Da dầu", "Nóng ẩm"],
    image: "/images/catalogue/makeup-fragrance-tech.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T12:30:00Z",
    likes: 333,
    comments: 30,
    sections: [
      { title: "Nền đẹp bắt đầu từ prep vừa đủ", body: ["Da dầu không nên prep quá dày. Dưỡng nhẹ, chống nắng không vón, chờ ổn rồi mới vào nền. Nếu lớp skincare trượt, foundation sẽ khó bám.", "Không cần phủ nền dày toàn mặt; che điểm ở vùng cần thiết thường tự nhiên và bền hơn."] },
      { title: "Set có chọn lọc", body: ["Phấn phủ ở vùng chữ T, khóe mũi và vùng dễ trôi. Setting spray có thể hỗ trợ nhưng không cứu được lớp nền quá dày.", "- Primer nếu thật sự khác biệt.\n- Foundation mỏng vừa.\n- Concealer đúng điểm.\n- Powder ở vùng dầu."] },
      { title: "Test dưới ánh sáng thật", body: ["Nền có thể xuống tone sau vài giờ. Test ngoài trời, trong văn phòng và dưới flash nếu dùng cho sự kiện. Chọn shade theo cổ/ngực và undertone, không chỉ muốn trắng hơn."] },
    ],
  }),
  makePost({
    title: "Makeup nam nhẹ không lộ nền",
    slug: "makeup-nam-nhe-khong-lo-nen",
    excerpt: "Makeup nam hằng ngày nên tập trung da đều màu, che điểm và finish tự nhiên thay vì phủ dày.",
    category: "Trang Điểm",
    tags: ["Makeup nam", "Base", "Grooming"],
    image: "/images/catalogue/makeup-fragrance-tech.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T12:40:00Z",
    likes: 286,
    comments: 22,
    sections: [
      { title: "Mục tiêu là da gọn hơn, không phải đổi mặt", body: ["Makeup nam nhẹ thường cần che quầng thâm, đỏ quanh mũi, mụn/thâm điểm và làm da bớt bóng. Skin tint hoặc concealer đúng màu thường đủ hơn foundation full coverage.", "Finish nên gần da thật, không quá lì bột hoặc bóng ướt."] },
      { title: "Cách layer", body: ["Dưỡng nhẹ, chống nắng ráo, che điểm mỏng, dùng phấn rất ít ở vùng dầu. Lông mày có thể chải gọn; môi dùng balm không bóng quá nếu muốn tự nhiên.", "Quan trọng là tán kỹ viền sản phẩm để không lộ mảng."] },
      { title: "Tẩy trang vẫn bắt buộc", body: ["Dù makeup nhẹ, sunscreen và concealer vẫn cần làm sạch. Nếu da dễ mụn, bỏ qua tẩy trang có thể làm vấn đề nặng hơn."] },
    ],
  }),
  makePost({
    title: "Son tint bền màu nhưng không khô môi",
    slug: "son-tint-ben-mau-nhung-khong-kho-moi",
    excerpt: "Chọn son tint theo độ bám, độ khô, stain và cách dưỡng môi trước/sau khi dùng.",
    category: "Trang Điểm",
    tags: ["Son tint", "Môi", "Makeup"],
    image: "/images/products/romand-juicy-lasting-tint.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T12:50:00Z",
    likes: 352,
    comments: 34,
    sections: [
      { title: "Bền màu thường đi kèm đánh đổi", body: ["Tint bám lâu có thể khô hơn, stain mạnh hơn hoặc khó tẩy hơn. Không có một cây son vừa bóng dưỡng, vừa bền cả ngày, vừa không dây ly trong mọi hoàn cảnh.", "Hãy chọn theo dịp: đi học/đi làm cần dễ dặm; đi ăn cần stain tốt; chụp ảnh cần màu rõ."] },
      { title: "Prep môi đúng", body: ["Tẩy da chết môi nhẹ khi cần, dùng balm trước nhưng lau bớt dầu thừa trước khi đánh tint. Nếu môi đang nứt chảy máu, ưu tiên phục hồi thay vì son bền.", "Sau ngày dùng son bền, tẩy trang môi kỹ và dưỡng lại."] },
      { title: "Đọc review son", body: ["Review son nên có màu môi gốc, ánh sáng, số lớp, thời gian bám và cảm giác sau vài giờ. Swatch tay không đủ để biết môi bạn có khô không."] },
    ],
  }),
  makePost({
    title: "Skin scent là gì",
    slug: "skin-scent-la-gi",
    excerpt: "Skin scent là nhóm mùi gần da, sạch, nhẹ và hợp môi trường hằng ngày nếu dùng đúng kỳ vọng.",
    category: "Mùi Hương",
    tags: ["Skin scent", "Fragrance", "Nước hoa"],
    image: "/images/catalogue/makeup-fragrance-tech.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T13:00:00Z",
    likes: 301,
    comments: 21,
    sections: [
      { title: "Skin scent là mùi ở khoảng cách gần", body: ["Skin scent thường cho cảm giác sạch, mềm, gần da, như musk, tea, soft woods hoặc mùi vải sạch. Nó không được thiết kế để lấn át phòng, nên nếu bạn muốn projection mạnh, skin scent có thể khiến bạn hụt kỳ vọng.", "Điểm hay là nó hợp văn phòng, lớp học và những nơi cần lịch sự."] },
      { title: "Cách test", body: ["Test trên da vài giờ, không chỉ giấy thử. Skin scent có thể rất khác giữa người này và người khác vì nhiệt độ da và mùi cơ thể.", "Đừng xịt quá nhiều để cố làm nó tỏa mạnh; như vậy dễ làm mùi gắt mà vẫn không đúng vai trò."] },
      { title: "Layering nhẹ", body: ["Body lotion không mùi hoặc cùng vibe sạch có thể giúp mùi mềm hơn. Tránh layer với body mist quá ngọt nếu muốn giữ cảm giác clean."] },
    ],
  }),
  makePost({
    title: "Body mist, hair mist, perfume khác nhau thế nào",
    slug: "body-mist-hair-mist-perfume-khac-nhau-the-nao",
    excerpt: "Ba nhóm mùi có độ đậm, cách dùng và vị trí xịt khác nhau; không nên dùng thay thế hoàn toàn cho nhau.",
    category: "Mùi Hương",
    tags: ["Body mist", "Hair mist", "Perfume"],
    image: "/images/products/miss-dior-eau-de-parfum.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T13:10:00Z",
    likes: 274,
    comments: 20,
    sections: [
      { title: "Body mist nhẹ và dễ xịt lại", body: ["Body mist thường nhẹ, dễ dùng sau tắm hoặc trong ngày. Độ lưu/tỏa thường thấp hơn perfume, nên hợp người thích mùi thoáng và không muốn gây chú ý quá mạnh.", "Nó không thay thế deodorant nếu vấn đề là mùi cơ thể do mồ hôi."] },
      { title: "Hair mist sinh ra cho tóc", body: ["Hair mist thường được thiết kế nhẹ hơn để dùng trên tóc. Không nên xịt perfume alcohol cao trực tiếp lên tóc khô/yếu quá thường xuyên vì có thể làm tóc khô hơn.", "Xịt lên lược hoặc phần đuôi tóc nhẹ là cách dễ kiểm soát."] },
      { title: "Perfume cần tiết chế", body: ["Perfume đậm hơn, dùng ít hơn và cần chú ý không gian. Một mùi đẹp trong buổi tối có thể quá mạnh trong thang máy hoặc phòng họp.", "Chọn sản phẩm theo nơi bạn xuất hiện nhiều nhất, không chỉ theo mùi bạn thích nhất trên giấy."] },
    ],
  }),
  makePost({
    title: "Nước hoa nam mùa hè không gắt",
    slug: "nuoc-hoa-nam-mua-he-khong-gat",
    excerpt: "Mùa hè nên ưu tiên citrus, tea, aquatic, clean musk hoặc soft woods với độ tỏa vừa phải.",
    category: "Mùi Hương",
    tags: ["Nước hoa nam", "Mùa hè", "Fragrance"],
    image: "/images/catalogue/makeup-fragrance-tech.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T13:20:00Z",
    likes: 319,
    comments: 26,
    sections: [
      { title: "Mùa hè khuếch đại mùi", body: ["Nhiệt và mồ hôi có thể làm mùi ngọt, amber hoặc smoky trở nên gắt hơn. Vì vậy nước hoa nam mùa hè nên ưu tiên sạch, thoáng, tươi và projection vừa phải.", "Citrus, tea, aquatic, clean musk, green notes hoặc soft woods thường dễ sống hơn trong khí hậu nóng ẩm."] },
      { title: "Xịt ít và đúng chỗ", body: ["Một đến ba xịt là đủ với nhiều mùi. Tránh xịt quá nhiều trước khi vào phòng kín. Nếu đi ngoài trời, có thể xịt lên áo ở vị trí không dễ ố thay vì da đang đổ mồ hôi nhiều.", "Đừng dùng nước hoa để che mùi sau gym; hãy xử lý vệ sinh và deodorant trước."] },
      { title: "Test drydown", body: ["Mùi mở đầu mát có thể khô xuống ngọt. Luôn test trên da vài giờ trước khi mua fullsize, đặc biệt với mùi nam mùa hè."] },
    ],
  }),
  makePost({
    title: "Skincare nam 3 bước",
    slug: "skincare-nam-3-buoc",
    excerpt: "Routine nam cơ bản: làm sạch dịu, dưỡng nhẹ và chống nắng dễ dùng mỗi ngày.",
    category: "Nam Giới",
    tags: ["Skincare nam", "Routine", "Grooming"],
    image: "/images/catalogue/hair-body-grooming.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T13:30:00Z",
    likes: 347,
    comments: 33,
    sections: [
      { title: "Ít bước nhưng phải đúng", body: ["Routine nam tốt nhất thường là routine làm được mỗi ngày. Ba bước nền gồm rửa mặt dịu, dưỡng nhẹ nếu cần và chống nắng ban ngày. Nếu một bước quá dính hoặc quá phức tạp, nó sẽ bị bỏ.", "Da dầu vẫn cần tránh cleanser quá gắt; căng rít sau rửa không phải sạch sâu tốt."] },
      { title: "Chọn texture dễ chịu", body: ["Dưỡng gel cream hoặc lotion nhẹ hợp nhiều người da dầu. Chống nắng nên ráo, không cay mắt khi đổ mồ hôi và dễ thoa lại.", "Nếu có mụn, thêm treatment chậm sau khi routine nền ổn."] },
      { title: "Tính cả tóc và râu", body: ["Sáp tóc, dầu râu, aftershave và dao cạo đều có thể ảnh hưởng da. Mụn trán, cổ hoặc lưng đôi khi đến từ grooming chứ không chỉ skincare mặt."] },
    ],
  }),
  makePost({
    title: "Pomade có gây mụn không",
    slug: "pomade-co-gay-mun-khong",
    excerpt: "Pomade, wax và sản phẩm tạo kiểu có thể gây bí nếu dính trán, thái dương, gối hoặc lưng.",
    category: "Nam Giới",
    tags: ["Pomade", "Mụn trán", "Grooming"],
    image: "/images/catalogue/hair-body-grooming.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T13:40:00Z",
    likes: 242,
    comments: 18,
    sections: [
      { title: "Có thể, nếu sản phẩm chạm da", body: ["Pomade/wax/gel không chỉ ở trên tóc. Chúng có thể dính trán, thái dương, cổ áo, gối hoặc chảy xuống lưng khi đổ mồ hôi. Với da dễ mụn, residue này có thể góp phần bí tắc.", "Không phải mọi pomade đều gây mụn, nhưng nếu mụn nằm đúng vùng tóc chạm vào da, hãy nghi ngờ."] },
      { title: "Cách giảm rủi ro", body: ["Dùng lượng ít hơn, tránh bôi sát chân tóc vùng trán, gội sạch cuối ngày và thay vỏ gối thường xuyên. Nếu sản phẩm khó gội, cần cleanser tóc phù hợp hơn.", "Khi tập gym, tránh để tóc có sản phẩm dính mồ hôi chảy xuống mặt/lưng."] },
      { title: "Khi nên đổi sản phẩm", body: ["Nếu mụn giảm rõ sau khi ngưng pomade 2-4 tuần, hãy đổi sang sản phẩm dễ gội sạch hơn hoặc ít dầu hơn."] },
    ],
  }),
  makePost({
    title: "Rụng tóc nam khi nào serum không đủ",
    slug: "rung-toc-nam-khi-nao-serum-khong-du",
    excerpt: "Serum da đầu chỉ là hỗ trợ; rụng tóc nam nhanh, từng mảng hoặc kèm viêm cần khám.",
    category: "Nam Giới",
    tags: ["Rụng tóc nam", "Serum tóc", "Da đầu"],
    image: "/images/catalogue/hair-body-grooming.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T13:50:00Z",
    likes: 276,
    comments: 24,
    sections: [
      { title: "Serum không xử lý mọi nguyên nhân", body: ["Rụng tóc có thể liên quan di truyền, hormone, stress, bệnh lý da đầu, thiếu hụt, thuốc hoặc sau bệnh. Serum bán lẻ không thể thay thế việc tìm nguyên nhân khi rụng rõ.", "Đặc biệt với nam giới, đường chân tóc lùi nhanh hoặc đỉnh đầu thưa dần nên được theo dõi sớm."] },
      { title: "Dấu hiệu serum không đủ", body: ["- Rụng từng mảng.\n- Rụng nhanh trong vài tuần.\n- Da đầu đỏ, đau, vảy, chảy dịch.\n- Đường ngôi/đỉnh đầu thưa nhanh.\n- Rụng kèm triệu chứng toàn thân.", "Trong các trường hợp này, mua thêm serum thường làm chậm thời điểm điều trị đúng."] },
      { title: "Làm gì trước khi khám", body: ["Chụp ảnh vùng rụng, ghi thời gian bắt đầu, sản phẩm đang dùng, thuốc/bệnh gần đây và tiền sử gia đình. Dữ liệu này hữu ích hơn việc mang một danh sách serum đã thử."] },
    ],
  }),
  makePost({
    title: "Laser trị nám cần hỏi gì trước khi làm",
    slug: "laser-tri-nam-can-hoi-gi-truoc-khi-lam",
    excerpt: "Laser trị nám cần đánh giá sắc tố, nguy cơ PIH, downtime, aftercare và kỳ vọng tái phát.",
    category: "Clinic / Treatment",
    tags: ["Laser", "Nám", "Clinic", "PIH"],
    image: "/images/catalogue/acne-sun-education.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T14:00:00Z",
    likes: 331,
    comments: 29,
    sections: [
      { title: "Nám không phải chỉ bắn laser là xong", body: ["Nám liên quan nắng, hormone, cơ địa và viêm. Laser có thể là một phần kế hoạch, nhưng nếu không kiểm soát chống nắng và trigger, nám dễ tái phát hoặc đậm hơn.", "Da dễ tăng sắc tố sau viêm cần đặc biệt thận trọng."] },
      { title: "Câu hỏi cần hỏi clinic", body: ["- Loại nám của tôi là gì?\n- Thiết bị/công nghệ nào, cơ chế gì?\n- Nguy cơ tăng sắc tố sau viêm ra sao?\n- Downtime bao lâu?\n- Sau làm phải tránh gì?\n- Nếu thâm đậm hơn thì xử lý thế nào?", "Clinic đáng tin sẽ nói cả giới hạn và rủi ro, không chỉ hứa sáng nhanh."] },
      { title: "Aftercare quyết định nhiều", body: ["Sau laser, chống nắng, phục hồi, tránh nhiệt và tránh hoạt chất mạnh theo hướng dẫn là bắt buộc. Nếu không làm aftercare, kết quả và an toàn đều giảm."] },
    ],
  }),
  makePost({
    title: "Sẹo rỗ: subcision, TCA cross, RF microneedling",
    slug: "seo-ro-subcision-tca-cross-rf-microneedling",
    excerpt: "Sẹo rỗ cần phân loại ice pick, boxcar, rolling trước khi chọn kỹ thuật.",
    category: "Clinic / Treatment",
    tags: ["Sẹo rỗ", "Subcision", "TCA cross", "RF microneedling"],
    image: "/images/catalogue/acne-sun-education.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T14:10:00Z",
    likes: 354,
    comments: 35,
    sections: [
      { title: "Không có một thủ thuật trị mọi loại sẹo", body: ["Ice pick, boxcar và rolling scar có hình thái khác nhau. TCA cross thường được nhắc với sẹo sâu hẹp; subcision với sẹo bị kéo dính; RF microneedling/laser có thể hỗ trợ texture và collagen. Chọn sai kỹ thuật dễ tốn tiền mà ít kết quả.", "Cần khám trực tiếp để phân loại sẹo, không chỉ gửi ảnh."] },
      { title: "Kỳ vọng theo nhiều buổi", body: ["Sẹo rỗ thường cải thiện theo phần trăm, không biến mất hoàn toàn sau một buổi. Kế hoạch tốt thường phối kỹ thuật theo loại sẹo và có khoảng nghỉ hồi phục.", "Hỏi số buổi dự kiến, downtime, rủi ro thâm, chi phí toàn liệu trình và aftercare."] },
      { title: "Rủi ro cần biết", body: ["Đỏ, sưng, bầm, tăng sắc tố, nhiễm trùng hoặc sẹo xấu hơn có thể xảy ra nếu sai chỉ định/aftercare. Chọn người thực hiện có chuyên môn quan trọng hơn săn deal."] },
    ],
  }),
  makePost({
    title: "Botox/filler: dấu hiệu biến chứng cần biết",
    slug: "botox-filler-dau-hieu-bien-chung-can-biet",
    excerpt: "Botox/filler là thủ thuật tiêm; cần hiểu dấu hiệu bất thường và kênh xử trí trước khi làm.",
    category: "Clinic / Treatment",
    tags: ["Botox", "Filler", "Biến chứng", "Clinic"],
    image: "/images/catalogue/makeup-fragrance-tech.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T14:20:00Z",
    likes: 388,
    comments: 42,
    sections: [
      { title: "Đây là thủ thuật, không phải dịch vụ spa nhẹ", body: ["Botox và filler liên quan giải phẫu, kỹ thuật tiêm, sản phẩm sử dụng và khả năng xử trí biến chứng. Trước khi làm, cần biết ai thực hiện, dùng sản phẩm gì, có giấy tờ không và khi có biến chứng thì liên hệ ai.", "Giá quá rẻ hoặc tư vấn mập mờ là tín hiệu cần dừng."] },
      { title: "Dấu hiệu cần liên hệ ngay", body: ["Sau filler, đau dữ dội, da tái/lạnh, đổi màu bất thường, nhìn mờ hoặc triệu chứng thần kinh là dấu hiệu cần xử trí khẩn. Sau botox, sụp mí, khó nuốt, khó thở hoặc yếu bất thường cần liên hệ chuyên môn.", "Không tự xử lý bằng mẹo mạng khi có dấu hiệu bất thường."] },
      { title: "Trước khi ký làm", body: ["Hỏi vùng tiêm, liều/lượng, sản phẩm, rủi ro, cách xử trí, thời gian hồi phục và lịch tái khám. Consent rõ ràng là một phần của dịch vụ an toàn."] },
    ],
  }),
  makePost({
    title: "Mụn trước kỳ kinh chăm thế nào",
    slug: "mun-truoc-ky-kinh-cham-the-nao",
    excerpt: "Mụn trước kỳ kinh cần theo dõi chu kỳ, giảm viêm và không đổi routine quá mạnh mỗi tháng.",
    category: "Beauty Lifestyle",
    tags: ["Mụn nội tiết", "Chu kỳ", "Lifestyle"],
    image: "/images/catalogue/skincare-foundation.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T14:30:00Z",
    likes: 315,
    comments: 28,
    sections: [
      { title: "Theo dõi pattern trước", body: ["Mụn trước kỳ kinh thường lặp lại theo thời điểm, hay ở cằm/quanh hàm với một số người. Ghi lại ngày nổi mụn, vùng mụn, mức đau và sản phẩm đang dùng trong 2-3 chu kỳ sẽ giúp đọc pattern tốt hơn.", "Đừng đổi toàn bộ routine chỉ vì vài nốt lặp theo chu kỳ."] },
      { title: "Chăm tại nhà", body: ["Giữ làm sạch dịu, dưỡng phục hồi, chống nắng và treatment chống viêm/bít tắc ở tần suất da chịu được. Không nặn mụn đau sâu.", "Nếu biết thường nổi mụn trước kỳ kinh, có thể chuẩn bị routine ổn định trước đó thay vì chờ bùng rồi đánh mạnh."] },
      { title: "Khi cần bác sĩ", body: ["Mụn đau sâu, tái phát nhiều, để sẹo hoặc kèm dấu hiệu rối loạn hormone nên được đánh giá chuyên môn. Mỹ phẩm chỉ hỗ trợ một phần với mụn nội tiết rõ."] },
    ],
  }),
  makePost({
    title: "Pregnancy-safe beauty",
    slug: "pregnancy-safe-beauty",
    excerpt: "Thai kỳ/sau sinh nên ưu tiên an toàn, phục hồi, chống nắng và hỏi bác sĩ trước hoạt chất có cảnh báo.",
    category: "Beauty Lifestyle",
    tags: ["Pregnancy-safe", "Sau sinh", "Skincare"],
    image: "/images/catalogue/skincare-foundation.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T14:40:00Z",
    likes: 401,
    comments: 37,
    sections: [
      { title: "Mục tiêu là an toàn trước", body: ["Trong thai kỳ/sau sinh, da có thể mụn, nám, khô hoặc nhạy cảm hơn. Routine nên ưu tiên làm sạch dịu, dưỡng phục hồi và chống nắng. Đừng tự dùng hoạt chất mạnh chỉ vì muốn xử lý nhanh.", "Retinoid và hydroquinone là các nhóm thường cần tránh hoặc hỏi bác sĩ tùy bối cảnh."] },
      { title: "Cách đọc sản phẩm", body: ["Đọc hoạt chất chính, cảnh báo, hướng dẫn dùng và hỏi bác sĩ nếu không chắc. Đừng chỉ dựa vào nhãn 'natural' hoặc 'clean' vì nguồn gốc tự nhiên không đảm bảo an toàn tuyệt đối.", "Nếu đang điều trị mụn/nám bằng thuốc, không tự phối thêm treatment mạnh."] },
      { title: "Khi nên đi khám", body: ["Nám lan nhanh, mụn đau/nang, rụng tóc nhiều, viêm da hoặc bất kỳ phản ứng mạnh nào trong thai kỳ/sau sinh nên được tư vấn chuyên môn."] },
    ],
  }),
  makePost({
    title: "Treatment quá đà nhận biết ra sao",
    slug: "treatment-qua-da-nhan-biet-ra-sao",
    excerpt: "Treatment quá đà thường biểu hiện bằng rát, đỏ, bong, châm chích và mụn kích ứng.",
    category: "Beauty Lifestyle",
    tags: ["Treatment", "Kích ứng", "Barrier"],
    image: "/images/catalogue/skincare-foundation.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T14:50:00Z",
    likes: 362,
    comments: 30,
    sections: [
      { title: "Dấu hiệu da quá tải", body: ["Da rát khi bôi dưỡng, đỏ dai dẳng, bong mảng, châm chích kéo dài, nổi mụn li ti ở vùng lạ hoặc da bóng căng bất thường là tín hiệu treatment quá đà.", "Nguyên nhân thường là phối nhiều active: acid, retinoid, vitamin C mạnh, peel, scrub hoặc cleanser gắt."] },
      { title: "Cách xử lý", body: ["Dừng/giảm active, giữ làm sạch dịu, dưỡng phục hồi và chống nắng. Không thêm tiếp sản phẩm mới để 'cứu da' nếu chưa biết da đang phản ứng với gì.", "Khi ổn lại, quay về treatment bằng tần suất thấp hơn trước."] },
      { title: "Khi cần đi khám", body: ["Sưng, nóng, đau, chảy dịch, mẩn lan rộng hoặc nghi viêm da tiếp xúc cần bác sĩ. Đừng cố chịu rát vì nghĩ treatment đang hoạt động."] },
    ],
  }),
  makePost({
    title: "Gel manicure bảo vệ móng thế nào",
    slug: "gel-manicure-bao-ve-mong-the-nao",
    excerpt: "Gel manicure đẹp bền hơn khi biết bảo vệ cuticle, tháo đúng cách và cho móng nghỉ khi cần.",
    category: "Nails / Mi / Mày",
    tags: ["Gel manicure", "Nail", "An toàn"],
    image: "/images/catalogue/makeup-fragrance-tech.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T15:00:00Z",
    likes: 244,
    comments: 16,
    sections: [
      { title: "Cuticle không phải phần thừa vô dụng", body: ["Cuticle giúp bảo vệ vùng móng mới mọc. Cắt/đẩy quá sâu có thể làm tăng nguy cơ viêm, đau hoặc nhiễm trùng. Nail đẹp không nên đánh đổi bằng vùng da quanh móng bị tổn thương.", "Hỏi salon cách vệ sinh dụng cụ và xử lý cuticle trước khi làm."] },
      { title: "Tháo gel đúng quan trọng như lúc làm", body: ["Tự bóc gel dễ làm móng mỏng, tách lớp và đau. Nếu gel cần mài quá mạnh mới tháo được, móng có thể yếu dần theo thời gian.", "Sau vài lần làm liên tục, nếu móng mềm, đau hoặc tách lớp, nên nghỉ và phục hồi."] },
      { title: "Dấu hiệu cần dừng", body: ["Móng đau, sưng quanh móng, đổi màu xanh/đen, tách móng hoặc có mủ là tín hiệu không nên phủ gel tiếp. Hãy xử lý an toàn trước khi làm đẹp lại."] },
    ],
  }),
  makePost({
    title: "Nối mi bị ngứa đỏ nên làm gì",
    slug: "noi-mi-bi-ngua-do-nen-lam-gi",
    excerpt: "Ngứa đỏ sau nối mi có thể liên quan keo, vệ sinh, form mi quá nặng hoặc kích ứng vùng mắt.",
    category: "Nails / Mi / Mày",
    tags: ["Nối mi", "Dị ứng", "Vùng mắt"],
    image: "/images/catalogue/makeup-fragrance-tech.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T15:10:00Z",
    likes: 271,
    comments: 25,
    sections: [
      { title: "Đỏ/ngứa không nên xem là bình thường", body: ["Sau nối mi, hơi cộm nhẹ có thể xảy ra, nhưng đỏ mắt, ngứa nhiều, sưng mí, đau hoặc chảy dịch không nên bị bỏ qua. Vùng mắt nhạy cảm và cần xử lý cẩn thận.", "Nguyên nhân có thể là keo, hơi keo, vệ sinh, form mi quá nặng hoặc nhiễm bẩn."] },
      { title: "Nên làm gì ngay", body: ["Không dụi mắt, không tự giật mi nối. Liên hệ salon để tháo an toàn nếu triệu chứng rõ. Nếu mắt đau, nhìn mờ, sưng nặng hoặc chảy dịch, nên đi khám.", "Tạm dừng makeup mắt và giữ vùng mắt sạch."] },
      { title: "Trước lần nối tiếp theo", body: ["Hỏi loại keo, cách vệ sinh, độ dày/độ cong phù hợp và quy trình xử lý dị ứng. Mi đẹp phải dễ sống cùng, không khiến mắt luôn khó chịu."] },
    ],
  }),
  makePost({
    title: "Dáng lông mày theo khuôn mặt",
    slug: "dang-long-may-theo-khuon-mat",
    excerpt: "Dáng mày nên đi theo xương mặt, mắt, màu tóc và mức bảo trì, không chỉ theo trend.",
    category: "Nails / Mi / Mày",
    tags: ["Lông mày", "Brow", "Dịch vụ làm đẹp"],
    image: "/images/catalogue/makeup-fragrance-tech.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T15:20:00Z",
    likes: 236,
    comments: 14,
    sections: [
      { title: "Mày đẹp là mày hợp mặt thật", body: ["Dáng mày quá sắc có thể đẹp trên ảnh nhưng nặng ngoài đời. Dáng quá ngang hoặc quá cong cũng có thể làm biểu cảm khác đi. Hãy xem xương chân mày, khoảng cách mắt, màu tóc và phong cách makeup hằng ngày.", "Không nên copy nguyên dáng của người khác nếu khuôn mặt khác."] },
      { title: "Bảo trì cũng là tiêu chí", body: ["Điêu khắc/phun/nhuộm mày cần tính thời gian phai, dặm, màu trổ và cách chăm sau làm. Nếu bạn thích makeup nhẹ, dáng mày nên mềm và dễ chỉnh.", "Hỏi rõ màu dùng, quá trình bong/phai và cách xử lý nếu không hợp."] },
      { title: "An toàn vùng mày", body: ["Da quanh mày cũng có thể kích ứng với thuốc nhuộm, wax hoặc keo. Nếu đỏ rát, sưng hoặc ngứa kéo dài, dừng dịch vụ và xử lý da trước."] },
    ],
  }),
  makePost({
    title: "LED mask có đáng tiền không",
    slug: "led-mask-co-dang-tien-khong",
    excerpt: "LED mask đáng cân nhắc khi thông số rõ, lịch dùng thực tế, bảo vệ mắt tốt và kỳ vọng đúng.",
    category: "Beauty Tech",
    tags: ["LED mask", "Beauty tech", "Skincare device"],
    image: "/images/catalogue/makeup-fragrance-tech.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T15:30:00Z",
    likes: 323,
    comments: 31,
    sections: [
      { title: "Đáng tiền khi bạn dùng đều và hiểu giới hạn", body: ["LED mask không phải phép màu. Nó có thể hỗ trợ một số mục tiêu chăm da tùy bước sóng/công suất/lịch dùng, nhưng không thay thế thuốc hoặc thủ thuật khi có bệnh da rõ.", "Nếu thiết bị không ghi thông số, hướng dẫn an toàn mắt hoặc chống chỉ định, nên thận trọng."] },
      { title: "Checklist trước khi mua", body: ["- Bước sóng/công suất có minh bạch không?\n- Có bảo vệ mắt không?\n- Lịch dùng có hợp bạn không?\n- Bảo hành, pin, vệ sinh thiết bị ra sao?\n- Da/thuốc hiện tại có chống chỉ định không?", "Một thiết bị đắt nhưng bỏ ngăn kéo sau 2 tuần thì không đáng tiền."] },
      { title: "Khi không nên tự dùng", body: ["Da đang viêm, nhiễm trùng, bỏng nắng, sau thủ thuật hoặc đang dùng thuốc gây nhạy sáng cần hỏi chuyên gia trước. Nếu dùng thấy đau/rát bất thường, dừng lại."] },
    ],
  }),
  makePost({
    title: "IPL tại nhà ai nên tránh",
    slug: "ipl-tai-nha-ai-nen-tranh",
    excerpt: "IPL tại nhà cần đọc màu da/màu lông, bảo vệ mắt, thuốc nhạy sáng và tình trạng da trước khi dùng.",
    category: "Beauty Tech",
    tags: ["IPL", "Triệt lông", "Beauty tech"],
    image: "/images/catalogue/makeup-fragrance-tech.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T15:40:00Z",
    likes: 284,
    comments: 23,
    sections: [
      { title: "Không phải ai cũng hợp IPL", body: ["IPL phụ thuộc tương quan màu da/màu lông và thông số thiết bị. Da quá tối, lông quá sáng, vùng da đang kích ứng hoặc người dùng thuốc gây nhạy sáng có thể không phù hợp.", "Luôn đọc bảng màu da/lông của hãng, không dùng theo cảm tính."] },
      { title: "Vùng cần tránh", body: ["Không dùng gần mắt nếu thiết bị không thiết kế cho vùng đó. Tránh vùng có vết thương, viêm, cháy nắng, tattoo hoặc nốt ruồi bất thường. Bảo vệ mắt theo hướng dẫn.", "Bắt đầu mức thấp và test vùng nhỏ trước."] },
      { title: "Dấu hiệu phải dừng", body: ["Đau rát mạnh, phồng rộp, bỏng, thâm bất thường hoặc kích ứng kéo dài là tín hiệu dừng và hỏi chuyên gia. Dùng nhiều hơn lịch hãng không làm kết quả nhanh hơn một cách an toàn."] },
    ],
  }),
  makePost({
    title: "Máy rửa mặt khi nào làm da yếu hơn",
    slug: "may-rua-mat-khi-nao-lam-da-yeu-hon",
    excerpt: "Máy rửa mặt có thể hữu ích với một số người nhưng ma sát quá mức dễ làm barrier yếu.",
    category: "Beauty Tech",
    tags: ["Máy rửa mặt", "Barrier", "Beauty tech"],
    image: "/images/catalogue/makeup-fragrance-tech.jpg",
    author: "360dep.vn Beauty Desk",
    avatar: "/brand/icon-192.png",
    createdAt: "2026-06-27T15:50:00Z",
    likes: 261,
    comments: 20,
    sections: [
      { title: "Sạch hơn không luôn tốt hơn", body: ["Máy rửa mặt thêm ma sát và rung lên da. Với da khỏe, dùng nhẹ có thể cho cảm giác sạch hơn. Với da đang treatment, mụn viêm, rosacea hoặc barrier yếu, ma sát có thể làm đỏ rát hơn.", "Căng rít sau rửa không phải dấu hiệu sạch tốt."] },
      { title: "Cách dùng giảm rủi ro", body: ["Dùng tần suất thấp, lực nhẹ, cleanser dịu và tránh vùng mụn viêm đau. Vệ sinh đầu máy thường xuyên để tránh tích tụ bẩn.", "Nếu da đỏ hơn, rát hơn hoặc bong sau khi dùng, hãy dừng vài tuần và quay lại rửa tay."] },
      { title: "Ai nên cân nhắc bỏ qua", body: ["Da rất nhạy cảm, đang dùng retinoid/acid mạnh, sau peel/laser hoặc đang viêm nên ưu tiên làm sạch bằng tay. Thiết bị không phải bước bắt buộc trong skincare."] },
    ],
  }),
]

export function getCatalogueReadPostByTitle(title: string) {
  return CATALOGUE_READ_POSTS.find((post) => post.title === title)
}

export function getCatalogueReadPost(idOrSlug: string) {
  return CATALOGUE_READ_POSTS.find((post) => post.id === idOrSlug || post.slug === idOrSlug) ?? null
}
