import type { CreatorProductEvent, ProductOffer, Review } from "@/lib/types"
import { RESEARCHED_PRODUCT_OFFERS, RESEARCHED_PRODUCT_REFERENCES } from "@/lib/product-research"

export const SAMPLE_PRODUCT_REFERENCES = [
  { id: "1", brand: "The Ordinary", name: "Hyaluronic Acid 2% + B5 Serum" },
  { id: "2", brand: "Maybelline New York", name: "Fit Me Matte + Poreless Foundation" },
  { id: "3", brand: "Bioderma", name: "Sensibio H2O Micellar Water" },
  { id: "4", brand: "MAC Cosmetics", name: "Powder Kiss Lip + Cheek Mousse" },
  { id: "5", brand: "Mise-en-Scene", name: "Perfect Serum Original" },
  { id: "6", brand: "CeraVe", name: "Hydrating Facial Cleanser" },
  { id: "7", brand: "Dior Beauty", name: "Miss Dior Eau de Parfum" },
  { id: "8", brand: "Vaseline", name: "Gluta-Hya Serum Burst Lotion Dewy Radiance" },
  ...RESEARCHED_PRODUCT_REFERENCES,
]

export const SAMPLE_PRODUCT_OFFERS: ProductOffer[] = [
  {
    id: "offer-1-shopee",
    product_id: "1",
    marketplace: "shopee",
    shop_name: "Shopee - The Ordinary HA B5 high-commission offer",
    seller_url: "https://shopee.vn/product/1207596898/24721120708",
    affiliate_url: "https://s.shopee.vn/2VpoDkq9ka",
    price_snapshot: "325.000đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  {
    id: "offer-2-shopee",
    product_id: "2",
    marketplace: "shopee",
    shop_name: "Shopee Mall - Maybelline Fit Me",
    seller_url: "https://shopee.vn/product/37252407/2356429108",
    affiliate_url: "https://s.shopee.vn/AAFF9rjVZ3",
    price_snapshot: "229.000đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  {
    id: "offer-3-shopee",
    product_id: "3",
    marketplace: "shopee",
    shop_name: "Shopee - Bioderma Sensibio bundle",
    seller_url: "https://shopee.vn/product/233692311/41263180850",
    affiliate_url: "https://s.shopee.vn/1gGh2G6njK",
    price_snapshot: "879.000đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  {
    id: "offer-4-shopee",
    product_id: "4",
    marketplace: "shopee",
    shop_name: "Shopee - MAC Powder Kiss Lip & Cheek Mousse high-sales offer",
    seller_url: "https://shopee.vn/product/1299246379/27605702533",
    affiliate_url: "https://s.shopee.vn/5L9zdc29FA",
    price_snapshot: "792.000đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  {
    id: "offer-5-shopee",
    product_id: "5",
    marketplace: "shopee",
    shop_name: "Shopee - Mise-en-Scene official offer",
    seller_url: "https://shopee.vn/product/1808224532/53559404132",
    affiliate_url: "https://s.shopee.vn/20tXQuDf3a",
    price_snapshot: "246.400đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  {
    id: "offer-6-shopee",
    product_id: "6",
    marketplace: "shopee",
    shop_name: "Shopee - CeraVe cleanser 473ml high-sales offer",
    seller_url: "https://shopee.vn/product/124409542/9821486012",
    affiliate_url: "https://s.shopee.vn/7AbdouMYVe",
    price_snapshot: "355.000đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  {
    id: "offer-7-shopee",
    product_id: "7",
    marketplace: "shopee",
    shop_name: "Shopee - Miss Dior Eau de Parfum 30ml official-style offer",
    seller_url: "https://shopee.vn/product/32022692/26830457076",
    affiliate_url: "https://s.shopee.vn/4LHST063Me",
    price_snapshot: "2.400.000đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  {
    id: "offer-8-shopee",
    product_id: "8",
    marketplace: "shopee",
    shop_name: "Shopee - Vaseline Gluta-Hya high-sales offer",
    seller_url: "https://shopee.vn/product/193849872/22410469736",
    affiliate_url: "https://s.shopee.vn/7VETz0OgIc",
    price_snapshot: "140.000đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  ...RESEARCHED_PRODUCT_OFFERS,
]

export const SAMPLE_CREATOR_PRODUCT_EVENTS: CreatorProductEvent[] = [
  {
    id: "evt-2026-06-30-yen-dan-maybelline-fit-me",
    creator_id: "10",
    product_id: "2",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@yendan7",
    source_title: "Yên Đan beauty/lifestyle profile",
    source_excerpt: "Creator được thêm vào kho theo dõi để bắt tín hiệu makeup và skincare routine.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi makeup nền và routine beauty đại chúng",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
  {
    id: "evt-2026-06-30-kim-chung-phan-micellar",
    creator_id: "37",
    product_id: "3",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@kimchungphan20",
    source_title: "Kim Chung Phan beauty/lifestyle profile",
    source_excerpt: "Creator được thêm vào kho theo dõi để bắt tín hiệu beauty đại chúng.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi makeup, tẩy trang và beauty lifestyle",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
  {
    id: "evt-2026-06-30-luong-lee-cerave-cleanser",
    creator_id: "95",
    product_id: "6",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@luonglee1404",
    source_title: "Lương Lee skincare/treatment profile",
    source_excerpt: "Creator được thêm vào kho theo dõi vì định vị skincare và treatment rõ.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi cleanser dịu nhẹ, phục hồi và treatment routine",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
  {
    id: "evt-2026-06-30-nga-nee-cerave-cleanser",
    creator_id: "98",
    product_id: "6",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@thuyngareview",
    source_title: "Nga nèe skincare review profile",
    source_excerpt: "Creator được thêm vào kho theo dõi cho review skincare thực dụng và chống nắng.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi skincare hằng ngày, chống nắng và làm sạch",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
]

export function reviewToTimelineEvent(review: Review): CreatorProductEvent {
  return {
    id: `review-event-${review.id}`,
    creator_id: review.kolid,
    product_id: review.productid,
    event_type: "reviewed",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn review",
    source_url: null,
    source_title: "Review nội bộ",
    source_excerpt: review.content,
    sentiment: review.rating >= 5 ? "positive" : review.rating >= 4 ? "mixed" : "negative",
    disclosure: review.ispr ? "pr" : "organic",
    usage_context: null,
    evidence_note: "Backfilled từ bảng reviews để không mất dữ liệu lịch sử cũ.",
    confidence: "medium",
  }
}
