import type { CreatorProductEvent, ProductOffer, Review } from "@/lib/types"
import { RESEARCHED_PRODUCT_OFFERS, RESEARCHED_PRODUCT_REFERENCES } from "@/lib/product-research"

export const SAMPLE_PRODUCT_REFERENCES = [
  { id: "1", brand: "The Ordinary", name: "Hyaluronic Acid 2% + B5 Serum" },
  { id: "2", brand: "Maybelline New York", name: "Fit Me Matte + Poreless Foundation" },
  { id: "3", brand: "Bioderma", name: "Sensibio H2O Micellar Water" },
  { id: "4", brand: "MAC Cosmetics", name: "Powder Kiss Lip + Cheek Mousse" },
  { id: "5", brand: "Mise-en-Scene", name: "Perfect Serum Original" },
  { id: "6", brand: "CeraVe", name: "Hydrating Facial Cleanser" },
  { id: "7", brand: "Dior Beauty", name: "Miss Dior Eau de Parfum" },
  { id: "8", brand: "Vaseline", name: "Gluta-Hya Serum Burst Lotion Dewy Radiance" },
  ...RESEARCHED_PRODUCT_REFERENCES,
]

export const SAMPLE_PRODUCT_OFFERS: ProductOffer[] = [
  {
    id: "offer-1-shopee",
    product_id: "1",
    marketplace: "official",
    shop_name: "The Ordinary official product page",
    seller_url: "https://theordinary.com/en-us/hyaluronic-acid-2-b5-serum-100425.html",
    affiliate_url: null,
    price_snapshot: "300.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
  {
    id: "offer-2-shopee",
    product_id: "2",
    marketplace: "shopee",
    shop_name: "Shopee Mall - Maybelline Fit Me",
    seller_url: "https://shopee.vn/product/37252407/2356429108",
    affiliate_url: "https://s.shopee.vn/AAFF9rjVZ3",
    price_snapshot: "229.000đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  {
    id: "offer-3-shopee",
    product_id: "3",
    marketplace: "shopee",
    shop_name: "Shopee - Bioderma Sensibio bundle",
    seller_url: "https://shopee.vn/product/233692311/41263180850",
    affiliate_url: "https://s.shopee.vn/1gGh2G6njK",
    price_snapshot: "879.000đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  {
    id: "offer-4-shopee",
    product_id: "4",
    marketplace: "official",
    shop_name: "MAC official product page",
    seller_url: "https://www.maccosmetics.com/product/13854/142086/products/makeup/lips/lipstick/powder-kiss-lip-cheek-mousse",
    affiliate_url: null,
    price_snapshot: "650.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
  {
    id: "offer-5-shopee",
    product_id: "5",
    marketplace: "shopee",
    shop_name: "Shopee - Mise-en-Scene official offer",
    seller_url: "https://shopee.vn/product/1808224532/53559404132",
    affiliate_url: "https://s.shopee.vn/20tXQuDf3a",
    price_snapshot: "246.400đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  {
    id: "offer-6-shopee",
    product_id: "6",
    marketplace: "official",
    shop_name: "CeraVe official product page",
    seller_url: "https://www.cerave.com/skincare/cleansers/hydrating-facial-cleanser",
    affiliate_url: null,
    price_snapshot: "380.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
  {
    id: "offer-7-shopee",
    product_id: "7",
    marketplace: "official",
    shop_name: "Dior official product page",
    seller_url: "https://www.dior.com/en_us/beauty/products/miss-dior-eau-de-parfum-Y0996347.html",
    affiliate_url: null,
    price_snapshot: "3.950.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
  {
    id: "offer-8-shopee",
    product_id: "8",
    marketplace: "shopee",
    shop_name: "Shopee - Vaseline Gluta-Hya high-sales offer",
    seller_url: "https://shopee.vn/product/193849872/22410469736",
    affiliate_url: "https://s.shopee.vn/7VETz0OgIc",
    price_snapshot: "140.000đ",
    stock_status: "in_stock",
    is_preferred: true,
    last_checked_at: "2026-07-02T00:00:00Z",
  },
  ...RESEARCHED_PRODUCT_OFFERS,
]

export const SAMPLE_CREATOR_PRODUCT_EVENTS: CreatorProductEvent[] = [
  {
    id: "evt-2026-04-10-halinh-goodndoc-b5",
    creator_id: "1",
    product_id: "1",
    event_type: "reviewed",
    event_date: "2026-04-10",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/top-5-serum-phuc-hoi-da-2026",
    source_title: "The Ordinary Hyaluronic Acid 2% + B5 Serum",
    source_excerpt: "Serum cấp ẩm HA/B5, hợp routine tối giản khi da thiếu nước hoặc cần phục hồi nhẹ.",
    sentiment: "positive",
    disclosure: "organic",
    usage_context: "Da thiếu nước, cần serum cấp ẩm trước kem dưỡng",
    evidence_note: "Seed từ review nội bộ ban đầu để chuẩn hóa mô hình timeline.",
    confidence: "medium",
  },
  {
    id: "evt-2026-04-06-goc-cua-ru-fit-me",
    creator_id: "2",
    product_id: "2",
    event_type: "reviewed",
    event_date: "2026-04-06",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/drugstore-makeup-haul-duoi-500k",
    source_title: "Kem nền Maybelline Fit Me Matte + Poreless",
    source_excerpt: "Độ che phủ ổn, kiềm dầu tốt nhưng xuống tone hơi nhanh.",
    sentiment: "mixed",
    disclosure: "pr",
    usage_context: "Makeup drugstore cho da dầu, layout hằng ngày",
    evidence_note: "Seed từ review nội bộ ban đầu để chuẩn hóa mô hình timeline.",
    confidence: "medium",
  },
  {
    id: "evt-2026-04-08-trinh-pham-loreal-micellar",
    creator_id: "3",
    product_id: "3",
    event_type: "recommended",
    event_date: "2026-04-08",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/huong-dan-chon-kem-chong-nang",
    source_title: "Bioderma Sensibio H2O Micellar Water",
    source_excerpt: "Một lựa chọn tẩy trang drugstore đáng mua, sạch sâu và không rát mắt.",
    sentiment: "positive",
    disclosure: "organic",
    usage_context: "Làm sạch cuối ngày, da nhạy cảm",
    evidence_note: "Seed từ review nội bộ ban đầu để chuẩn hóa mô hình timeline.",
    confidence: "medium",
  },
  {
    id: "evt-2026-04-04-call-me-duy-mac-powder-kiss",
    creator_id: "4",
    product_id: "4",
    event_type: "reviewed",
    event_date: "2026-04-04",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/skincare-routine-da-dau-mun",
    source_title: "MAC Powder Kiss Lip + Cheek Mousse",
    source_excerpt: "Màu son lên chuẩn, chất son mềm mịn, độ bám màu trung bình.",
    sentiment: "mixed",
    disclosure: "pr",
    usage_context: "Makeup môi, son lì mềm",
    evidence_note: "Seed từ review nội bộ ban đầu để chuẩn hóa mô hình timeline.",
    confidence: "medium",
  },
  {
    id: "evt-2026-04-02-bong-bee-batiste-dry-shampoo",
    creator_id: "60",
    product_id: "5",
    event_type: "used",
    event_date: "2026-04-02",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/giai-cuu-toc-hu-ton-sau-tay-nhuom",
    source_title: "Mise-en-Scene Perfect Serum Original",
    source_excerpt: "Serum dưỡng tóc giúp giảm rối, thêm bóng và làm mềm phần đuôi tóc khô xơ.",
    sentiment: "positive",
    disclosure: "organic",
    usage_context: "Tóc khô xơ, tóc sau tẩy nhuộm cần giảm rối và thêm độ bóng",
    evidence_note: "Seed fallback đã chuyển sang creator haircare xác định được, loại bỏ hồ sơ Bồng Bềnh không đủ tín hiệu.",
    confidence: "medium",
  },
  {
    id: "evt-2026-03-30-halinh-vaseline-gluta-hya",
    creator_id: "1",
    product_id: "8",
    event_type: "reviewed",
    event_date: "2026-03-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/so-sanh-sua-duong-the-trang-da",
    source_title: "Sữa dưỡng thể Vaseline Gluta-Hya",
    source_excerpt: "Texture nhẹ, hợp thời tiết nóng ẩm; hiệu quả cần dùng đều trong nhiều tuần.",
    sentiment: "positive",
    disclosure: "organic",
    usage_context: "Bodycare dưỡng sáng, dùng hằng ngày",
    evidence_note: "Seed từ bài fallback ban đầu để chuẩn hóa mô hình timeline.",
    confidence: "medium",
  },
  {
    id: "evt-2026-06-30-yen-dan-maybelline-fit-me",
    creator_id: "10",
    product_id: "2",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@yendan7",
    source_title: "Yên Đan beauty/lifestyle profile",
    source_excerpt: "Creator được thêm vào kho theo dõi để bắt tín hiệu makeup và skincare routine.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi makeup nền và routine beauty đại chúng",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
  {
    id: "evt-2026-06-30-kim-chung-phan-micellar",
    creator_id: "37",
    product_id: "3",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@kimchungphan20",
    source_title: "Kim Chung Phan beauty/lifestyle profile",
    source_excerpt: "Creator được thêm vào kho theo dõi để bắt tín hiệu beauty đại chúng.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi makeup, tẩy trang và beauty lifestyle",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
  {
    id: "evt-2026-06-30-luong-lee-cerave-cleanser",
    creator_id: "95",
    product_id: "6",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@luonglee1404",
    source_title: "Lương Lee skincare/treatment profile",
    source_excerpt: "Creator được thêm vào kho theo dõi vì định vị skincare và treatment rõ.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi cleanser dịu nhẹ, phục hồi và treatment routine",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
  {
    id: "evt-2026-06-30-nga-nee-cerave-cleanser",
    creator_id: "98",
    product_id: "6",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@thuyngareview",
    source_title: "Nga nèe skincare review profile",
    source_excerpt: "Creator được thêm vào kho theo dõi cho review skincare thực dụng và chống nắng.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi skincare hằng ngày, chống nắng và làm sạch",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
]

export function reviewToTimelineEvent(review: Review): CreatorProductEvent {
  return {
    id: `review-event-${review.id}`,
    creator_id: review.kolid,
    product_id: review.productid,
    event_type: "reviewed",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn review",
    source_url: null,
    source_title: "Review nội bộ",
    source_excerpt: review.content,
    sentiment: review.rating >= 5 ? "positive" : review.rating >= 4 ? "mixed" : "negative",
    disclosure: review.ispr ? "pr" : "organic",
    usage_context: null,
    evidence_note: "Backfilled từ bảng reviews để không mất dữ liệu lịch sử cũ.",
    confidence: "medium",
  }
}
