import type { CreatorProductEvent, ProductOffer, Review } from "@/lib/types"

export const SAMPLE_PRODUCT_REFERENCES = [
  { id: "1", brand: "GoodnDoc", name: "Tinh chất phục hồi da B5 GoodnDoc" },
  { id: "2", brand: "Maybelline", name: "Kem nền Maybelline Fit Me Matte + Poreless" },
  { id: "3", brand: "L'Oreal", name: "Nước tẩy trang L'Oreal Micellar Water 3-in-1" },
  { id: "4", brand: "MAC", name: "Son kem lì MAC Powder Kiss Liquid Lipcolour" },
  { id: "5", brand: "Batiste", name: "Dầu gội khô Batiste Dry Shampoo" },
  { id: "6", brand: "Cerave", name: "Sữa rửa mặt Cerave Hydrating Cleanser" },
  { id: "7", brand: "Narciso Rodriguez", name: "Nước hoa nữ Narciso Rodriguez For Her EDP" },
  { id: "8", brand: "Vaseline", name: "Sữa dưỡng thể Vaseline Gluta-Hya" },
]

export const SAMPLE_PRODUCT_OFFERS: ProductOffer[] = [
  {
    id: "offer-1-shopee",
    product_id: "1",
    marketplace: "shopee",
    shop_name: "Shopee Mall / official reseller",
    seller_url: "https://shopee.vn/search?keyword=GoodnDoc%20B5%20serum",
    affiliate_url: null,
    price_snapshot: "350.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
  {
    id: "offer-2-shopee",
    product_id: "2",
    marketplace: "shopee",
    shop_name: "Maybelline official / Shopee Mall",
    seller_url: "https://shopee.vn/search?keyword=Maybelline%20Fit%20Me%20Matte%20Poreless",
    affiliate_url: null,
    price_snapshot: "180.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
  {
    id: "offer-3-shopee",
    product_id: "3",
    marketplace: "shopee",
    shop_name: "L'Oreal Paris official / Shopee Mall",
    seller_url: "https://shopee.vn/search?keyword=L%27Oreal%20Micellar%20Water%203-in-1",
    affiliate_url: null,
    price_snapshot: "150.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
  {
    id: "offer-4-shopee",
    product_id: "4",
    marketplace: "shopee",
    shop_name: "MAC official / Shopee Mall",
    seller_url: "https://shopee.vn/search?keyword=MAC%20Powder%20Kiss%20Liquid%20Lipcolour",
    affiliate_url: null,
    price_snapshot: "650.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
  {
    id: "offer-5-shopee",
    product_id: "5",
    marketplace: "shopee",
    shop_name: "Batiste official / Shopee Mall",
    seller_url: "https://shopee.vn/search?keyword=Batiste%20Dry%20Shampoo",
    affiliate_url: null,
    price_snapshot: "120.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
  {
    id: "offer-6-shopee",
    product_id: "6",
    marketplace: "shopee",
    shop_name: "CeraVe official / Shopee Mall",
    seller_url: "https://shopee.vn/search?keyword=CeraVe%20Hydrating%20Cleanser",
    affiliate_url: null,
    price_snapshot: "380.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
  {
    id: "offer-7-shopee",
    product_id: "7",
    marketplace: "shopee",
    shop_name: "Narciso Rodriguez official reseller",
    seller_url: "https://shopee.vn/search?keyword=Narciso%20Rodriguez%20For%20Her%20EDP",
    affiliate_url: null,
    price_snapshot: "2.500.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
  {
    id: "offer-8-shopee",
    product_id: "8",
    marketplace: "shopee",
    shop_name: "Vaseline official / Shopee Mall",
    seller_url: "https://shopee.vn/search?keyword=Vaseline%20Gluta-Hya",
    affiliate_url: null,
    price_snapshot: "140.000đ",
    stock_status: "unknown",
    is_preferred: true,
    last_checked_at: "2026-06-30T00:00:00Z",
  },
]

export const SAMPLE_CREATOR_PRODUCT_EVENTS: CreatorProductEvent[] = [
  {
    id: "evt-2026-04-10-halinh-goodndoc-b5",
    creator_id: "1",
    product_id: "1",
    event_type: "reviewed",
    event_date: "2026-04-10",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/top-5-serum-phuc-hoi-da-2026",
    source_title: "Serum phục hồi da B5 GoodnDoc",
    source_excerpt: "Phục hồi da ổn, thấm nhanh và không bết dính; hợp da đang treatment.",
    sentiment: "positive",
    disclosure: "organic",
    usage_context: "Da đang treatment, cần phục hồi hàng rào bảo vệ da",
    evidence_note: "Seed từ review nội bộ ban đầu để chuẩn hóa mô hình timeline.",
    confidence: "medium",
  },
  {
    id: "evt-2026-04-06-goc-cua-ru-fit-me",
    creator_id: "2",
    product_id: "2",
    event_type: "reviewed",
    event_date: "2026-04-06",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/drugstore-makeup-haul-duoi-500k",
    source_title: "Kem nền Maybelline Fit Me Matte + Poreless",
    source_excerpt: "Độ che phủ ổn, kiềm dầu tốt nhưng xuống tone hơi nhanh.",
    sentiment: "mixed",
    disclosure: "pr",
    usage_context: "Makeup drugstore cho da dầu, layout hằng ngày",
    evidence_note: "Seed từ review nội bộ ban đầu để chuẩn hóa mô hình timeline.",
    confidence: "medium",
  },
  {
    id: "evt-2026-04-08-trinh-pham-loreal-micellar",
    creator_id: "3",
    product_id: "3",
    event_type: "recommended",
    event_date: "2026-04-08",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/huong-dan-chon-kem-chong-nang",
    source_title: "Nước tẩy trang L'Oreal Micellar Water 3-in-1",
    source_excerpt: "Một lựa chọn tẩy trang drugstore đáng mua, sạch sâu và không rát mắt.",
    sentiment: "positive",
    disclosure: "organic",
    usage_context: "Làm sạch cuối ngày, da nhạy cảm",
    evidence_note: "Seed từ review nội bộ ban đầu để chuẩn hóa mô hình timeline.",
    confidence: "medium",
  },
  {
    id: "evt-2026-04-04-call-me-duy-mac-powder-kiss",
    creator_id: "4",
    product_id: "4",
    event_type: "reviewed",
    event_date: "2026-04-04",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/skincare-routine-da-dau-mun",
    source_title: "Son kem lì MAC Powder Kiss Liquid Lipcolour",
    source_excerpt: "Màu son lên chuẩn, chất son mềm mịn, độ bám màu trung bình.",
    sentiment: "mixed",
    disclosure: "pr",
    usage_context: "Makeup môi, son lì mềm",
    evidence_note: "Seed từ review nội bộ ban đầu để chuẩn hóa mô hình timeline.",
    confidence: "medium",
  },
  {
    id: "evt-2026-04-02-bong-benh-batiste-dry-shampoo",
    creator_id: "5",
    product_id: "5",
    event_type: "used",
    event_date: "2026-04-02",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/giai-cuu-toc-hu-ton-sau-tay-nhuom",
    source_title: "Dầu gội khô Batiste Dry Shampoo",
    source_excerpt: "Giải pháp làm sạch nhanh cho tóc bết, phù hợp khi cần cứu nguy trong một phút.",
    sentiment: "positive",
    disclosure: "organic",
    usage_context: "Tóc bết, tóc sau tẩy nhuộm cần giảm tần suất gội",
    evidence_note: "Seed từ bài fallback ban đầu để chuẩn hóa mô hình timeline.",
    confidence: "medium",
  },
  {
    id: "evt-2026-03-30-halinh-vaseline-gluta-hya",
    creator_id: "1",
    product_id: "8",
    event_type: "reviewed",
    event_date: "2026-03-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn seed",
    source_url: "/blog/so-sanh-sua-duong-the-trang-da",
    source_title: "Sữa dưỡng thể Vaseline Gluta-Hya",
    source_excerpt: "Texture nhẹ, hợp thời tiết nóng ẩm; hiệu quả cần dùng đều trong nhiều tuần.",
    sentiment: "positive",
    disclosure: "organic",
    usage_context: "Bodycare dưỡng sáng, dùng hằng ngày",
    evidence_note: "Seed từ bài fallback ban đầu để chuẩn hóa mô hình timeline.",
    confidence: "medium",
  },
  {
    id: "evt-2026-06-30-yen-dan-maybelline-fit-me",
    creator_id: "10",
    product_id: "2",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@yendan7",
    source_title: "Yên Đan beauty/lifestyle profile",
    source_excerpt: "Creator được thêm vào kho theo dõi để bắt tín hiệu makeup và skincare routine.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi makeup nền và routine beauty đại chúng",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
  {
    id: "evt-2026-06-30-kim-chung-phan-micellar",
    creator_id: "37",
    product_id: "3",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@kimchungphan20",
    source_title: "Kim Chung Phan beauty/lifestyle profile",
    source_excerpt: "Creator được thêm vào kho theo dõi để bắt tín hiệu beauty đại chúng.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi makeup, tẩy trang và beauty lifestyle",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
  {
    id: "evt-2026-06-30-luong-lee-cerave-cleanser",
    creator_id: "95",
    product_id: "6",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@luonglee1404",
    source_title: "Lương Lee skincare/treatment profile",
    source_excerpt: "Creator được thêm vào kho theo dõi vì định vị skincare và treatment rõ.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi cleanser dịu nhẹ, phục hồi và treatment routine",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
  {
    id: "evt-2026-06-30-nga-nee-cerave-cleanser",
    creator_id: "98",
    product_id: "6",
    event_type: "first_seen",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "TikTok",
    source_url: "https://www.tiktok.com/@thuyngareview",
    source_title: "Nga nèe skincare review profile",
    source_excerpt: "Creator được thêm vào kho theo dõi cho review skincare thực dụng và chống nắng.",
    sentiment: "neutral",
    disclosure: "unknown",
    usage_context: "Theo dõi skincare hằng ngày, chống nắng và làm sạch",
    evidence_note: "Profile live-check 06/2026; event khởi tạo để bắt đầu timeline theo dõi.",
    confidence: "low",
  },
]

export function reviewToTimelineEvent(review: Review): CreatorProductEvent {
  return {
    id: `review-event-${review.id}`,
    creator_id: review.kolid,
    product_id: review.productid,
    event_type: "reviewed",
    event_date: "2026-06-30",
    observed_at: "2026-06-30T00:00:00Z",
    source_platform: "360dep.vn review",
    source_url: null,
    source_title: "Review nội bộ",
    source_excerpt: review.content,
    sentiment: review.rating >= 5 ? "positive" : review.rating >= 4 ? "mixed" : "negative",
    disclosure: review.ispr ? "pr" : "organic",
    usage_context: null,
    evidence_note: "Backfilled từ bảng reviews để không mất dữ liệu lịch sử cũ.",
    confidence: "medium",
  }
}
