/**
 * Emits supabase/seed/demo.sql from lib/data.ts: the same sample freelancers,
 * portfolio and reviews the prototype used, as real rows behind real auth users.
 *
 *   npm run demo:sql
 *
 * Only for local development and the labelled demo environment. Every review is
 * backed by a completed booking, so a rating is a fact the database can defend
 * rather than a number in a constant.
 */
import { createHash } from "node:crypto"
import { writeFileSync } from "node:fs"
import { getTemplate, getVariant } from "../lib/catalog"
import { PROS, PRO_SERVICES, REVIEWS, WORKS } from "../lib/data"
import { DISTRICT_COORDS } from "../lib/geo"
import { POLICY, commissionFor } from "../lib/pricing"

const OUT = "supabase/seed/demo.sql"
const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const arr = (xs: string[]) => (xs.length ? `array[${xs.map(q).join(", ")}]::text[]` : "'{}'::text[]")

/** Stable ids, so re-running the seed updates the same rows. */
function uuidFor(kind: string, key: string) {
  const h = createHash("md5").update(`dep360:${kind}:${key}`).digest("hex")
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-8${h.slice(17, 20)}-${h.slice(20, 32)}`
}

const e164 = (phone: string) => `+84${phone.replace(/\D/g, "").replace(/^0/, "")}`
const coords = (city: string, district: string) => DISTRICT_COORDS[city]?.[district] ?? [21.0278, 105.8342]

const lines: string[] = [
  "-- Generated by scripts/gen-demo-sql.ts from lib/data.ts. Run `npm run demo:sql`.",
  "-- Sample data for local development and the labelled demo. Not real people.",
  "",
]

// Auth users ------------------------------------------------------------------
// Phone accounts, already confirmed: locally there is no SMS provider to call.
function authUser(id: string, phone: string, name: string) {
  lines.push(
    `insert into auth.users (instance_id, id, aud, role, phone, phone_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)`,
    `values ('00000000-0000-0000-0000-000000000000', ${q(id)}, 'authenticated', 'authenticated', ${q(phone)}, now(),`,
    `  '{"provider":"phone","providers":["phone"]}', jsonb_build_object('full_name', ${q(name)}), now(), now(), '', '', '', '')`,
    `on conflict (id) do update set phone = excluded.phone, raw_user_meta_data = excluded.raw_user_meta_data;`,
    `insert into auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)`,
    `values (gen_random_uuid(), ${q(id)}, jsonb_build_object('sub', ${q(id)}, 'phone', ${q(phone)}), 'phone', ${q(phone)}, now(), now(), now())`,
    `on conflict (provider, provider_id) do nothing;`,
    "",
  )
}

// Freelancers -----------------------------------------------------------------

lines.push("-- Freelancers ---------------------------------------------------------------")
for (const pro of PROS) {
  const id = uuidFor("pro", pro.id)
  const [lat, lng] = coords(pro.city, pro.district)
  authUser(id, e164(pro.phone), pro.name)
  lines.push(
    `update public.accounts set full_name = ${q(pro.name)}, active_role = 'pro',`,
    `  avatar_path = ${pro.avatar ? q(pro.avatar) : "null"} where id = ${q(id)};`,
    `insert into public.pros (id, slug, title, bio, highlights, categories, city, district, lat, lng, areas,`,
    `  home_service, studio_address, max_travel_km, years_exp, accepting_jobs, published, identity_status)`,
    `values (${q(id)}, ${q(pro.id)}, ${q(pro.title)}, ${q(pro.bio)}, ${arr(pro.highlights)},`,
    `  array[${pro.categories.map(q).join(", ")}]::public.category_id[], ${q(pro.city)}, ${q(pro.district)}, ${lat}, ${lng}, ${arr(pro.areas)},`,
    `  ${pro.homeService}, ${pro.studioAddress ? q(pro.studioAddress) : "null"}, ${pro.maxTravelKm}, ${pro.yearsExp}, true, true, ${q(pro.identity)})`,
    `on conflict (id) do update set title = excluded.title, bio = excluded.bio, highlights = excluded.highlights,`,
    `  categories = excluded.categories, city = excluded.city, district = excluded.district,`,
    `  lat = excluded.lat, lng = excluded.lng, areas = excluded.areas, home_service = excluded.home_service,`,
    `  studio_address = excluded.studio_address, max_travel_km = excluded.max_travel_km, years_exp = excluded.years_exp;`,
    // The guards keep platform-owned columns out of client hands, so set them here.
    `update public.pros set published = true, identity_status = ${q(pro.identity)} where id = ${q(id)};`,
    "",
  )
  // Mon–Sat 09:00–19:00. A freelancer edits this in the studio later.
  for (const weekday of [1, 2, 3, 4, 5, 6]) {
    lines.push(
      `insert into public.working_hours (pro_id, weekday, start_min, end_min) values (${q(id)}, ${weekday}, 540, 1140)`,
      `on conflict (pro_id, weekday, start_min) do nothing;`,
    )
  }
  lines.push("")
}

// Listings --------------------------------------------------------------------

lines.push("-- Listings ------------------------------------------------------------------")
for (const listing of PRO_SERVICES) {
  const proId = uuidFor("pro", listing.proId)
  lines.push(
    `insert into public.pro_services (pro_id, template_id, active) values (${q(proId)}, ${q(listing.templateId)}, ${listing.active})`,
    `on conflict (pro_id, template_id) do update set active = excluded.active;`,
  )
  for (const [variantId, price] of Object.entries(listing.prices)) {
    lines.push(
      `insert into public.pro_service_prices (pro_id, template_id, variant_id, price) values (${q(proId)}, ${q(listing.templateId)}, ${q(variantId)}, ${price})`,
      `on conflict (pro_id, template_id, variant_id) do update set price = excluded.price;`,
    )
  }
}
lines.push("")

// Portfolio -------------------------------------------------------------------

lines.push("-- Portfolio -----------------------------------------------------------------")
WORKS.forEach((work, i) => {
  lines.push(
    `insert into public.works (id, pro_id, template_id, title, description, image_paths, is_cover, sort_order)`,
    `values (${q(uuidFor("work", work.id))}, ${q(uuidFor("pro", work.proId))}, ${q(work.templateId)}, ${q(work.title)},`,
    `  ${q(work.description)}, ${arr(work.images)}, ${i === 0}, ${i})`,
    `on conflict (id) do update set title = excluded.title, description = excluded.description,`,
    `  image_paths = excluded.image_paths, template_id = excluded.template_id, sort_order = excluded.sort_order;`,
  )
})
lines.push("")

// Reviewers, their completed bookings, and the reviews -------------------------

lines.push("-- Customers who left the reviews -------------------------------------------")
const reviewers = [...new Set(REVIEWS.map((r) => r.author))]
reviewers.forEach((name, i) => {
  const id = uuidFor("customer", name)
  // A valid Vietnamese mobile number: +84 then 9 digits. The demo reviewers get
  // a reserved block so they never collide with a real one.
  authUser(id, `+849${81000000 + i}`, name)
  const [lat, lng] = coords("Hà Nội", "Đống Đa")
  lines.push(
    `update public.accounts set full_name = ${q(name)} where id = ${q(id)};`,
    `insert into public.addresses (id, account_id, label, city, district, detail, lat, lng, is_default)`,
    `values (${q(uuidFor("address", name))}, ${q(id)}, 'Nhà', 'Hà Nội', 'Đống Đa', 'Địa chỉ mẫu', ${lat}, ${lng}, true)`,
    `on conflict (id) do nothing;`,
    "",
  )
})

lines.push("-- A review needs a completed booking behind it -----------------------------")
for (const review of REVIEWS) {
  const proId = uuidFor("pro", review.proId)
  const customerId = uuidFor("customer", review.author)
  const bookingId = uuidFor("booking", review.id)
  // The service name in the review text tells us which listing it was.
  const [serviceName, variantLabel] = review.serviceName.split(" · ")
  const template = PRO_SERVICES.map((l) => getTemplate(l.templateId)!).find((t) => t.name === serviceName)
  const listing = PRO_SERVICES.find((l) => l.proId === review.proId && l.templateId === template?.id)
  const variant = template?.variants.find((v) => v.label === variantLabel)
  if (!template || !listing || !variant) {
    throw new Error(`Review ${review.id} names a service no listing matches: ${review.serviceName}`)
  }
  const price = listing.prices[variant.id] ?? variant.suggestedPrice
  const commission = commissionFor(price)
  const pro = PROS.find((p) => p.id === review.proId)!
  const [proLat, proLng] = coords(pro.city, pro.district)

  lines.push(
    `insert into public.bookings (id, customer_id, pro_id, template_id, variant_id, quantity, source,`,
    `  starts_at, duration_min, buffer_min, at_home, city, district, address, lat, lng,`,
    `  service_price, distance_km, travel_fee, urgent_fee, commission_rate, commission,`,
    `  payment_method, status, confirm_by, confirmed_at, completed_at, created_at)`,
    `values (${q(bookingId)}, ${q(customerId)}, ${q(proId)}, ${q(template.id)}, ${q(variant.id)}, 1, 'direct',`,
    `  (${q(review.date)}::date + interval '14 hours') at time zone 'Asia/Ho_Chi_Minh', ${variant.durationMin}, 30, true,`,
    `  'Hà Nội', 'Đống Đa', 'Địa chỉ mẫu', ${proLat}, ${proLng},`,
    `  ${price}, 2.0, 0, 0, ${POLICY.commissionRate}, ${commission},`,
    `  'cash', 'completed', (${q(review.date)}::date + interval '12 hours') at time zone 'Asia/Ho_Chi_Minh',`,
    `  (${q(review.date)}::date + interval '12 hours') at time zone 'Asia/Ho_Chi_Minh',`,
    `  (${q(review.date)}::date + interval '16 hours') at time zone 'Asia/Ho_Chi_Minh',`,
    `  (${q(review.date)}::date - interval '2 days') at time zone 'Asia/Ho_Chi_Minh')`,
    `on conflict (id) do nothing;`,
    `insert into public.wallet_entries (pro_id, booking_id, kind, amount, note)`,
    `values (${q(proId)}, ${q(bookingId)}, 'commission', ${-commission}, 'Hoa hồng job hoàn thành')`,
    `on conflict (booking_id, kind) do nothing;`,
    `insert into public.reviews (booking_id, pro_id, customer_id, rating, tags, body, photo_paths, reply, replied_at, created_at)`,
    `values (${q(bookingId)}, ${q(proId)}, ${q(customerId)}, ${review.rating}, ${arr(review.tags)}, ${q(review.text)},`,
    `  ${arr(review.photo ? [review.photo] : [])}, ${review.reply ? q(review.reply) : "null"},`,
    `  ${review.reply ? `${q(review.date)}::date` : "null"}, ${q(review.date)}::date)`,
    `on conflict (booking_id) do update set rating = excluded.rating, body = excluded.body,`,
    `  tags = excluded.tags, photo_paths = excluded.photo_paths, reply = excluded.reply;`,
    "",
  )
}

// A freelancer starts with a topped-up wallet so the demo is not blocked by debt.
lines.push(
  "-- Prepaid wallet top-up so the demo freelancers can keep accepting jobs -----",
  ...PROS.flatMap((pro) => {
    const id = uuidFor("pro", pro.id)
    return [
      `insert into public.wallet_entries (id, pro_id, kind, amount, ref, note)`,
      `values (${q(uuidFor("topup", pro.id))}, ${q(id)}, 'topup', 2000000, 'DEMO', 'Nạp ví mẫu')`,
      `on conflict (id) do nothing;`,
    ]
  }),
  "",
  "-- Metrics are derived, never typed in.",
  "select public.recompute_pro_metrics();",
  "",
)

writeFileSync(OUT, lines.join("\n"))
console.log(`Wrote ${OUT} (${PROS.length} freelancers, ${WORKS.length} works, ${REVIEWS.length} reviews).`)
