/**
 * Emits supabase/seed/catalog.sql from the TypeScript catalogue, so the price
 * bands the UI shows and the ones the database enforces can never drift apart.
 *
 *   npm run catalog:sql          # regenerate
 *   npm run catalog:check        # fail if the committed file is stale (CI)
 *
 * Production does not run seed files, so a catalogue change also needs a
 * migration. This prints the same upserts for the given trades, to paste into one:
 *
 *   npx tsx scripts/gen-catalog-sql.ts --templates=photo,model
 *
 * The output is idempotent: safe to run against an existing database.
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs"
import { CATALOG, verticalOf } from "../lib/catalog"
import type { ServiceTemplate } from "../lib/types"
import { DISTRICT_COORDS } from "../lib/geo"
import { POLICY } from "../lib/pricing"

const OUT = "supabase/seed/catalog.sql"
const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const arr = (xs: string[]) => `array[${xs.map(q).join(", ")}]::text[]`

const lines: string[] = [
  "-- Generated by scripts/gen-catalog-sql.ts from lib/catalog.ts, lib/geo.ts and lib/pricing.ts.",
  "-- Do not edit by hand: run `npm run catalog:sql`.",
  "",
  "-- Fee policy ----------------------------------------------------------------",
  "update public.fee_policy set",
  `  commission_rate = ${POLICY.commissionRate},`,
  `  confirm_within_hours = ${POLICY.confirmWithinHours},`,
  `  late_cancel_rate = ${POLICY.lateCancelRate},`,
  `  free_travel_km = ${POLICY.freeTravelKm},`,
  `  travel_fee_per_km = ${POLICY.travelFeePerKm},`,
  `  travel_fee_cap = ${POLICY.travelFeeCap},`,
  `  urgent_within_hours = ${POLICY.urgentWithinHours},`,
  `  urgent_fee = ${POLICY.urgentFee},`,
  `  min_lead_minutes = ${POLICY.minLeadMinutes},`,
  `  free_cancel_hours = ${POLICY.freeCancelHours},`,
  "  updated_at = now()",
  "where id;",
  "",
  "-- Districts -----------------------------------------------------------------",
]

let order = 0
for (const [city, districts] of Object.entries(DISTRICT_COORDS)) {
  for (const [district, [lat, lng]] of Object.entries(districts)) {
    lines.push(
      `insert into public.districts (city, district, lat, lng, sort_order) values (${q(city)}, ${q(district)}, ${lat}, ${lng}, ${order++})`,
      "  on conflict (city, district) do update set lat = excluded.lat, lng = excluded.lng, sort_order = excluded.sort_order;",
    )
  }
}

lines.push("", "-- Service catalogue ---------------------------------------------------------")

/** Upserts for one service and its options. sort_order is its place in CATALOG. */
function templateSql(t: ServiceTemplate, sortOrder: number): string[] {
  const out = [
    `insert into public.service_templates (id, category, name, description, includes, studio_only, on_location, deliverable, delivery_days, requires_verification, active, sort_order) values (`,
    `  ${q(t.id)}, ${q(t.category)}, ${q(t.name)}, ${q(t.description)}, ${arr(t.includes)}, ${Boolean(t.studioOnly)}, ${Boolean(t.onLocation)}, ${t.deliverable ? q(t.deliverable) : "null"}, ${t.deliveryDays ?? "null"}, ${Boolean(t.requiresVerification)}, true, ${sortOrder})`,
    "  on conflict (id) do update set category = excluded.category, name = excluded.name,",
    "    description = excluded.description, includes = excluded.includes,",
    "    studio_only = excluded.studio_only, on_location = excluded.on_location, deliverable = excluded.deliverable,",
    "    delivery_days = excluded.delivery_days, requires_verification = excluded.requires_verification,",
    "    active = excluded.active, sort_order = excluded.sort_order;",
  ]
  t.variants.forEach((v, vi) => {
    out.push(
      `insert into public.service_variants (template_id, id, label, duration_min, min_price, max_price, suggested_price, per_person, max_quantity, sort_order) values (`,
      `  ${q(t.id)}, ${q(v.id)}, ${q(v.label)}, ${v.durationMin}, ${v.minPrice}, ${v.maxPrice}, ${v.suggestedPrice}, ${Boolean(v.perPerson)}, ${v.maxQuantity ?? 1}, ${vi})`,
      "  on conflict (template_id, id) do update set label = excluded.label, duration_min = excluded.duration_min,",
      "    min_price = excluded.min_price, max_price = excluded.max_price, suggested_price = excluded.suggested_price,",
      "    per_person = excluded.per_person, max_quantity = excluded.max_quantity, sort_order = excluded.sort_order;",
    )
  })
  return out
}

const only = process.argv.find((a) => a.startsWith("--templates="))
if (only) {
  const verticals = only.slice("--templates=".length).split(",")
  const picked = CATALOG.flatMap((t, ti) => (verticals.includes(verticalOf(t.category)) ? templateSql(t, ti) : []))
  process.stdout.write(picked.join("\n") + "\n")
  process.exit(0)
}

CATALOG.forEach((t, ti) => lines.push(...templateSql(t, ti)))

// Anything dropped from the catalogue stops being offered but is kept, because
// existing bookings and listings still point at it.
lines.push(
  "",
  "-- Retired services stay in the table: bookings still reference them.",
  `update public.service_templates set active = false where id <> all (array[${CATALOG.map((t) => q(t.id)).join(", ")}]);`,
  "",
)

const sql = lines.join("\n")

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : ""
  if (current !== sql) {
    console.error(`${OUT} is out of date. Run \`npm run catalog:sql\` and commit the result.`)
    process.exit(1)
  }
  console.log(`${OUT} is up to date.`)
} else {
  writeFileSync(OUT, sql)
  console.log(`Wrote ${OUT} (${CATALOG.length} services, ${CATALOG.reduce((n, t) => n + t.variants.length, 0)} options).`)
}
